"use client";

import { createContext, useContext, useState, useEffect } from "react";

const DEFAULT_LANGUAGE = "fr";
const SUPPORTED_LANGUAGES = new Set(["fr", "ht"]);
const LANGUAGE_STORAGE_KEY = "language";

function normalizeLanguage(value = "") {
  const normalizedValue = String(value || "").trim().toLowerCase();
  return SUPPORTED_LANGUAGES.has(normalizedValue) ? normalizedValue : DEFAULT_LANGUAGE;
}

const translations = {
  fr: {
    // Navigation
    home: "Accueil",
    feed: "Communauté",
    writeComment: "Écrire un commentaire...",
    report: "Signaler",
    confirmReport: "Voulez-vous signaler ce post ?",
    groups: "Groupes",
    doctor: "Pédiatre",
    pediatre: "Pédiatrie",
    healthHub: "Espace santé",
    gynecology: "Gynécologie",
    psychology: "Psychologie",
    tools: "Outils",
    guides: "Guides",
    games: "Jeux",
    boutique: "Boutique",
    messages: "Messages",
    favorites: "Favoris",
    notifications: "Notifications",
    profile: "Profil",
    login: "Connexion",
    register: "S'inscrire",
    logout: "Déconnexion",
    
    // Boutique
    sellItem: "Vendre un article",
    searchPlaceholder: "Rechercher un article...",
    filters: "Filtres",
    clearFilters: "Effacer les filtres",
    sortBy: "Trier par",
    priceLowToHigh: "Prix croissant",
    priceHighToLow: "Prix décroissant",
    newest: "Plus récent",
    localOnly: "Uniquement local",
    marketplace: "Place du marché",
    myFavorites: "Mes favoris",
    addToFavorites: "Ajouter aux favoris",
    removeFromFavorites: "Retirer des favoris",
    postFirstItem: "Soyez la première à publier un article !",
    clearAll: "Effacer tout",
    applyFilters: "Appliquer les filtres",
    reset: "Réinitialiser",
    allLocations: "Toutes les lieux",
    allCategories: "Toutes les catégories",
    allConditions: "Tous les états",
    
    // Categories
    vetements: "Vêtements",
    jouets: "Jouets",
    mobilier: "Mobilier",
    livres: "Livres",
    poussettes: "Poussettes & Sièges",
    transport: "Transport",
    autres: "Autres",
    
    // Messages
    conversations: "Conversations",
    sendMessage: "Envoyer",
    typeMessage: "Tapez votre message...",
    noMessages: "Aucun message",
    startConversation: "Commencer une conversation",
    
    // Reviews
    reviews: "Avis",
    rating: "Note",
    writeReview: "Donner votre avis",
    yourReview: "Votre avis",
    noReviews: "Aucun avis",
    notRatedYet: "Pas encore noté",
    beFirstToReview: "Soyez le premier à donner votre avis !",
    
    // Notifications
    markAllAsRead: "Tout marquer comme lu",
    noNotifications: "Aucune notification",
    
    // Admin
    adminPanel: "Administration",
    managePosts: "Gérer les publications",
    manageUsers: "Gérer les utilisateurs",
    statistics: "Statistiques",
    
    // Site texts
    title: "Lakou Manman — Communauté de mères haïtiennes",
    description: "Une plateforme interactive où les mères haïtiennes trouvent conseils, soutien et partagent leurs expériences.",
    welcomeBanner: "Bienvenue dans Lakou Manman — Communauté de mères haïtiennes du monde entier",
    aboutTitle: "À propos de Lakou Manman",
    mission: "Une communauté de mères haïtiennes du monde entier pour partager, apprendre et se soutenir mutuellement.",
    siteDescription: "Une plateforme interactive où les mères haïtiennes trouvent conseils, soutien et partagent leurs expériences avec une communauté engagée, des ressources pratiques, du contenu de confiance, et l'ambition de devenir le véritable réseau social des mères.",
    
    // Home page features
    communityTitle: "Communauté",
    communityDesc: "Posez vos questions, partagez vos expériences et trouvez du soutien auprès des autres mamans haïtiennes.",
    supportGroupsTitle: "Groupes d'entraide",
    supportGroupsDesc: "Rejoignez des groupes pour discuter de sujets précis et obtenir des conseils d'experts.",
    pediatricAdviceTitle: "Conseils pédiatriques",
    pediatricAdviceDesc: "Trouvez des recommandations de médecins pour la santé et le bien-être de votre bébé.",
    educationalResourcesTitle: "Ressources éducatives",
    educationalResourcesDesc: "Accédez à nos guides et articles sur la santé maternelle et infantile.",
    practicalToolsTitle: "Outils pratiques",
    practicalToolsDesc: "Calculettes de grossesse, suivi alimentaire et autres outils pour les mamans.",
    localResourcesTitle: "Services locaux",
    localResourcesDesc: "Découvrez les services de santé et d'accompagnement près de chez vous.",
    
    // Common
    loading: "Chargement...",
    save: "Enregistrer",
    cancel: "Annuler",
    close: "Fermer",
    delete: "Supprimer",
    edit: "Modifier",
    confirm: "Confirmer",
    retry: "Réessayer",
    back: "Retour",
    next: "Suivant",
    submit: "Envoyer",
    required: "Obligatoire",
    optional: "Optionnel",
    
    // Home page buttons
    createAccount: "Créer mon compte",
    seeCommunity: "Voir la communauté",
    
    // Stats
    statMothers: "mères dans la communauté",
    statSupport: "espace questions & soutien",
    statCities: "villes de la diaspora actives",
    statGroups: "groupes communautaires",
    
    // Section titles
    featuresTitle: "Ce que Lakou Manman vous offre",
    featuresSubtitle: "Tout ce dont une mère a besoin, en un seul lieu.",
    testimonialsTitle: "Ce que nos mamans disent",
    testimonialsSubtitle: "Découvrez les expériences de notre communauté",
    
    // CTA Section
    ctaTitle: "Rejoignez la communauté dès aujourd'hui",
    ctaDescription: "Inscrivez-vous gratuitement, créez votre profil et commencez à partager avec d'autres mamans.",
    ctaButton: "S'inscrire maintenant",
    ctaLogin: "J'ai déjà un compte",
    
    // Footer
    footerNavigation: "Navigation",
    footerInformation: "Information",
    footerMedicalDisclaimer: "Tout le contenu médical est à titre informatif uniquement.",
    footerMedicalAdvice: "Pour un avis médical, contactez directement un professionnel de santé.",
    footerMadeWith: "Made with ❤️ pour les mamans haïtiennes",
    
    // Stripe Invoice Information
    invoiceCompanyName: "Lakou Manman S.A.",
    invoiceAddress: "Port-au-Prince, Haïti",
    invoiceEmail: "contact@lakou-manman.com",
    invoicePhone: "+509 32 58 93 91",
    invoiceWebsite: "www.lakou-manman.com",
    invoiceTaxId: "HT-123456789",
    
    // Invoice Footer Text
    invoiceFooterTitle: "Lakou Manman - La communauté des mamans haïtiennes",
    invoiceFooterDesc: "Merci pour votre confiance. Ensemble, nous construisons une communauté solidaire.",
    invoiceFooterNote: "Tous les prix sont en HTG. Taxes incluses si applicables.",
    invoicePaymentInfo: "Paiement sécurisé traité via Stripe",
    invoiceSupportContact: "Pour toute question : contact@lakou-manman.com",
    
    // Payment Form
    paymentError: "Une erreur est survenue lors du paiement",
    paymentSuccessMessage: "Paiement réussi avec succès !",
    processingPayment: "Traitement du paiement...",
    payNow: "Payer maintenant",
    paymentProcessing: "Traitement du paiement en cours",
    paymentComplete: "Paiement terminé",
    paymentFailed: "Échec du paiement",
    downloadReceipt: "Télécharger le reçu",
    
    // MonCash Payment
    yourMonCashNumber: "Votre numéro MonCash",
    yourOrangeMoneyNumber: "Votre numéro Orange Money",
    yourNatCashNumber: "Votre numéro NatCash",
    important: "Important",
    smsConfirmationText: "Vous recevrez un SMS de confirmation sur ce numéro pour valider le paiement.",
    amountDebitedText: "Le montant sera débité de votre compte MonCash/Orange Money.",
    validPhoneRequired: "Veuillez entrer un numéro de téléphone valide.",
    paymentMethodLabel: "Méthode de paiement",
    moncashOption: "MonCash",
    orangeMoneyOption: "Orange Money",
    natcashOption: "NatCash",
    paymentHeaderMoncash: "Paiement MonCash",
    paymentHeaderOrange: "Paiement Orange Money",
    paymentHeaderNatcash: "Transfert NatCash à vérifier",
    securePaymentMoncash: "Paiement sécurisé via MonCash",
    securePaymentOrange: "Paiement sécurisé via Orange Money",
    securePaymentNatcash: "Transfert NatCash réel avec vérification manuelle",
    payWithMonCash: "Payer avec MonCash",
    payWithOrangeMoney: "Payer avec Orange Money",
    payWithNatCash: "J'ai payé avec NatCash",
    natcashReferenceLabel: "Référence NatCash",
    natcashReferencePlaceholder: "Ex: NAT123456 ou référence envoyée après paiement",
    natcashReceiverNumber: "Numéro NatCash du vendeur",
    natcashReceiverUnavailable: "Aucun numéro NatCash n'est encore configuré pour cet article. Contactez le support avant de payer.",
    natcashPaymentPending: "TRANSFERT NATCASH À VÉRIFIER !",
    natcashManualMode: "Transfert réel vérifié manuellement",
    paymentReferenceRequired: "Veuillez saisir la référence de la transaction NatCash.",
    paymentNoteLabel: "Note de paiement",
    paymentNotePlaceholder: "Ex: paiement envoyé depuis le numéro de mon conjoint",
    moncashPaymentPending: "PAIEMENT MONCASH EN COURS!",
    moncashPaymentSuccess: "PAIEMENT MONCASH RÉUSSI!",
    transactionDetails: "Détails Transaction:",
    article: "Article",
    amount: "Montant",
    lakouManmanCommission: "Commission Lakou Manman",
    sellerAmount: "Montant Vendeur",
    paymentInfo: "Informations Paiement",
    transactionId: "Transaction ID",
    reference: "Référence",
    phone: "Téléphone",
    method: "Méthode",
    mode: "Mode",
    realMoncash: "MonCash Réel",
    demoMode: "Mode Demo",
    date: "Date",
    downloadInvoice: "Voulez-vous télécharger votre facture ?",
    actionRequired: "ACTION REQUISE:",
    checkSmsText: "Vérifiez vos SMS sur",
    receiveMoncashText: "Vous devriez recevoir un message de MonCash pour confirmer ce paiement.",
    replyYesText: "Répondez \"OUI\" au SMS pour finaliser l'achat.",
    downloadProvisionalInvoice: "Voulez-vous télécharger une facture provisoire ?",
    paymentError: "ERREUR PAIEMENT",
    errorOccurred: "Une erreur est survenue",
    error: "ERREUR",
    paymentProcessingError: "Impossible de traiter le paiement. Veuillez réessayer.",
    
    // Invoice
    invoiceTitle: "FACTURE LAKOU MANMAN",
    invoiceNumber: "Numéro",
    clientInfo: "INFORMATIONS CLIENT",
    name: "Nom",
    articleDetails: "DÉTAILS ARTICLE",
    quantity: "Quantité",
    price: "Prix",
    total: "Total",
    financialSummary: "RÉCAPITULATIF FINANCIER",
    subtotal: "Sous-total",
    totalPaid: "TOTAL PAYÉ",
    platformSubtitle: "Plateforme Communautaire Haïtienne",
    thankYouForTrust: "Merci pour votre confiance !",
    contact: "Contact",
    
    // Seller Form
    sellerMonCashNumber: "Numéro MonCash (vendeur)",
    receivePaymentsText: "Pour recevoir les paiements directement sur votre compte MonCash",
    sellerNatCashNumber: "Numéro NatCash (vendeur)",
    receiveNatCashPaymentsText: "Pour recevoir les paiements NatCash directement sur votre compte NatCash",
    
    // Delivery Options
    deliveryOptions: "Options de livraison",
    pickup: "Retrait sur place",
    pickupDescription: "Récupérer directement auprès du vendeur",
    homeDelivery: "Livraison à domicile",
    deliveryDescription: "Livraison à votre adresse",
    free: "GRATUIT",
    calculated: "Calculé",
    deliveryAddress: "Adresse de livraison",
    deliveryAddressPlaceholder: "Entrez votre adresse complète...",
    deliveryInfo: "Information livraison",
    deliveryFeeCalculated: "Les frais de livraison seront calculés selon la distance",
    deliveryFee: "Frais de livraison",
    
    // Groups
    groupJoined: "Groupe rejoint !",
    groupJoinedMessage: "Vous avez rejoint le groupe avec succès",
    errorJoiningGroup: "Erreur",
    errorJoiningGroupMessage: "Impossible de rejoindre le groupe",
    welcomeToGroup: "Bienvenue dans le groupe !",
    members: "membres",
    created: "Créé",
    joinGroup: "Rejoindre le groupe",
    member: "Membre",
    share: "Partager",
    settings: "Paramètres",
    createPost: "Créer un message",
    postPlaceholder: "Partagez quelque chose avec le groupe...",
    publish: "Publier",
    photo: "Photo",
    video: "Vidéo",
    reviews: "avis",
    admin: "Admin",
    moderator: "Modérateur",
    groupInfo: "Informations du groupe",
    location: "Localisation",
    activity: "Activité",
    veryActive: "Très actif",
    contactAdmin: "Contacter l'admin",
    groupAdmin: "Admin du groupe",
    message: "Message",
    email: "Email",
    
    // Pediatrician
    bookAppointment: "Prendre rendez-vous",
    consultationVideo: "Consultation vidéo",
    sendMessage: "Envoyer un message",
    educationalVideos: "Vidéos éducatives",
    articlesResources: "Articles et ressources",
    contactDoctor: "Contacter le docteur",
    yourName: "Votre nom",
    yourEmail: "Votre email",
    yourPhone: "Votre téléphone",
    consultationReason: "Raison de la consultation",
    message: "Message",
    namePlaceholder: "Entrez votre nom",
    emailPlaceholder: "votre@email.com",
    reasonPlaceholder: "Ex: Contrôle de routine, fièvre, etc.",
    messagePlaceholder: "Décrivez votre situation...",
    messageSent: "Message envoyé avec succès !",
    quickContact: "Contact rapide",
    callNow: "Appeler maintenant",
    whatsapp: "WhatsApp",
    sendEmail: "Envoyer un email",
    pediatriciansDirectory: "Pédiatres disponibles",
    pediatriciansDirectoryDesc: "Cet espace est ouvert à plusieurs pédiatres, organisés par ville.",
    allCities: "Toutes les villes",
    selectPediatrician: "Choisir ce pédiatre",
    selectedPediatrician: "Pédiatre sélectionné",
    city: "Ville",
    consultationFees: "Tarifs consultation",
    inPerson: "En personne",
    clinicConsultation: "Consultation clinique",
    virtual: "Virtuelle",
    videoConsultation: "Consultation vidéo",
    emergency: "Urgence",
    emergencyConsultation: "Consultation d'urgence",
    availability: "Disponibilité",
    monday: "Lundi",
    tuesday: "Mardi",
    wednesday: "Mercredi",
    thursday: "Jeudi",
    friday: "Vendredi",
    saturday: "Samedi",
    sunday: "Dimanche",
    hospitalInfo: "Information hôpital",
    getDirections: "Obtenir l'itinéraire",
    views: "vues",
    
    // Tools
    toolsTitle: "Outils pour mamans",
    toolsDescription: "Des outils pratiques pour vous aider dans votre quotidien de maman",
    availableTools: "Outils disponibles",
    selectTool: "Sélectionnez un outil",
    selectToolDesc: "Choisissez un outil dans la liste pour commencer",
    pregnancyCalculator: "Calculateur grossesse",
    pregnancyCalculatorDesc: "Calculez votre date d'accouchement et suivez votre grossesse",
    babyGrowth: "Croissance bébé",
    babyGrowthDesc: "Suivez la croissance et le développement de votre bébé",
    temperatureTracker: "Suivi température",
    temperatureTrackerDesc: "Enregistrez et suivez la température de votre enfant",
    emergencyContacts: "Contacts d'urgence",
    emergencyContactsDesc: "Accédez rapidement aux contacts d'urgence pédiatriques",
    vaccinationSchedule: "Calendrier vaccinal",
    vaccinationScheduleDesc: "Modèle de calendrier vaccinal pour suivre les vaccins de l'enfance à l'adolescence",
    vaccinationModelTitle: "Modèle de calendrier vaccinal",
    ageGroup: "Tranche d'âge",
    recommendedVaccines: "Vaccins recommandés",
    vaccinationReminder: "Ce calendrier est un modèle indicatif. Confirmez toujours avec un pédiatre ou un centre de santé.",
    vaccinationBirthStage: "À la naissance",
    vaccination6WeeksStage: "6 semaines",
    vaccination10WeeksStage: "10 semaines",
    vaccination14WeeksStage: "14 semaines",
    vaccination9MonthsStage: "9 mois",
    vaccination12MonthsStage: "12 mois",
    vaccination15MonthsStage: "15 mois",
    vaccination18MonthsStage: "18 mois",
    vaccination4To6YearsStage: "4 à 6 ans",
    vaccination9To14YearsStage: "9 à 14 ans",
    vaccination15To18YearsStage: "15 à 18 ans",
    vaccinationBirthVaccines: "BCG, Polio 0, Hépatite B selon le protocole local",
    vaccination6WeeksVaccines: "Pentavalent 1, Polio 1, Rotavirus 1, Pneumocoque 1",
    vaccination10WeeksVaccines: "Pentavalent 2, Polio 2, Rotavirus 2, Pneumocoque 2",
    vaccination14WeeksVaccines: "Pentavalent 3, Polio 3, Pneumocoque 3",
    vaccination9MonthsVaccines: "Rougeole-Rubéole, Vitamine A",
    vaccination12MonthsVaccines: "Rappels et suivi selon le centre de santé",
    vaccination15MonthsVaccines: "Rappels de la petite enfance selon le protocole local",
    vaccination18MonthsVaccines: "DTC/Polio/ROR ou autres rappels selon le programme national",
    vaccination4To6YearsVaccines: "Rappels préscolaires selon le programme national",
    vaccination9To14YearsVaccines: "Vaccin HPV et autres doses recommandées selon disponibilité et protocole local",
    vaccination15To18YearsVaccines: "Rappels adolescents, tétanos-diphtérie et mise à jour du carnet selon le centre de santé",
    nutritionGuide: "Guide nutrition",
    nutritionGuideDesc: "Conseils nutritionnels adaptés à l'âge de votre enfant",
    developmentMilestones: "Étapes développement",
    developmentMilestonesDesc: "Suivez les étapes clés du développement de votre enfant",
    communitySupport: "Soutien communautaire",
    communitySupportDesc: "Connectez-vous avec d'autres mamans pour du soutien",
    lastPeriodDate: "Date des dernières règles",
    cycleLength: "Durée du cycle (jours)",
    pregnancyResults: "Résultats grossesse",
    weeks: "Semaines",
    days: "Jours",
    trimester: "Trimestre",
    daysLeft: "Jours restants",
    dueDate: "Date d'accouchement prévue",
    birthDate: "Date de naissance",
    birthWeight: "Poids de naissance (kg)",
    currentWeight: "Poids actuel (kg)",
    currentHeight: "Taille actuelle (cm)",
    growthResults: "Résultats croissance",
    daysOld: "Jours",
    monthsOld: "Mois",
    weightGain: "Gain poids (kg)",
    dailyGain: "Gain/jour (g)",
    growthNormal: "Croissance normale",
    consultDoctor: "Consultez un professionnel de santé",
    temperature: "Température (°C)",
    symptoms: "Symptômes associés",
    cough: "Toux",
    runnyNose: "Nez qui coule",
    headache: "Mal de tête",
    fatigue: "Fatigue",
    lossAppetite: "Perte d'appétit",
    vomiting: "Vomissements",
    hypothermia: "Hypothermie",
    normal: "Normal",
    fever: "Fièvre légère",
    moderateFever: "Fièvre modérée",
    highFever: "Fièvre élevée",
    recommendations: "Recommandations",
    monitorTemp: "Surveillez la température toutes les 4 heures",
    hydrate: "Assurez une bonne hydratation",
    rest: "Repos recommandé",
    giveMedication: "Donnez du paracétamol si nécessaire",
    monitorClosely: "Surveillance rapprochée",
    consultIfWorsens: "Consultez si la fièvre persiste > 48h",
    consultImmediately: "Consultez un médecin immédiatement",
    emergencySigns: "Signes d'urgence",
    monitorClosely: "Surveillance rapprochée",
    keepHydrated: "Maintenez l'hydratation",
    difficultyBreathing: "Difficulté à respirer",
    blueLips: "Lèvres ou visage bleu",
    unconscious: "Perte de conscience",
    seizures: "Convulsions",
    severeBleeding: "Saignement sévère",
    callEmergency: "Appeler l'urgence (114)",
    emergencyServices: "Services d'urgence",
    pediatricEmergency: "Urgence pédiatrique",
    poisonControl: "Centre antipoison",
    drBeaubrun: "Dr Beaubrun (Pédiatre)",
    hospitalEmergency: "Urgence Hôpital",
    call: "Appeler",
    
    // Header & Footer
    aboutUs: "À propos",
    howItWorks: "Comment ça marche",
    features: "Fonctionnalités",
    testimonials: "Témoignages",
    helpCenter: "Centre d'aide",
    footerHelpCenter: "Centre d'aide",
    footerContact: "Contact",
    footerAboutUs: "À propos",
    footerLegal: "Légal",
    footerPrivacyPolicy: "Politique de confidentialité",
    footerTermsOfService: "Conditions d'utilisation",
    faq: "FAQ",
    reportIssue: "Signaler un problème",
    privacyPolicy: "Politique de confidentialité",
    termsOfService: "Conditions d'utilisation",
    cookiePolicy: "Politique cookies",
    guidelines: "Directives communautaires",
    groups: "Groupes",
    platform: "Plateforme",
    support: "Soutien",
    services: "Services",
    legal: "Légal",
    footerDescription: "Lakou Manman est la plateforme de référence pour les mamans haïtiennes. Connectez-vous, partagez, et accédez à des ressources précieuses pour votre bien-être et celui de vos enfants.",
    communityFeature: "Communauté Active",
    communityFeatureDesc: "Rejoignez des milliers de mamans",
    expertFeature: "Accès Experts",
    expertFeatureDesc: "Consultez des pédiatres, psychologues, gynécologues et autres professionnels qualifiés",
    safetyFeature: "Sécurité",
    safetyFeatureDesc: "Plateforme sécurisée et modérée",
    allRightsReserved: "Tous droits réservés.",
    madeWith: "Fait avec",
    forHaitianMoms: "pour les mamans haïtiennes",
    footerCommunityPhrase: "Une communauté de mères haïtiennes du monde entier pour partager, apprendre et se soutenir mutuellement.",
    privacy: "Confidentialité",
    terms: "Conditions",
    cookies: "Cookies",
    community: "Communauté",
    safety: "Sécurité",
    inclusion: "Inclusion",
    excellence: "Excellence",
    innovation: "Innovation",
    safetyDesc: "Protéger et accompagner nos membres dans un cadre fiable.",
    supportDesc: "Offrir un accompagnement humain, bienveillant et utile à chaque maman.",
    inclusionDesc: "Valoriser chaque maman haïtienne, où qu'elle vive et quel que soit son parcours.",
    excellenceDesc: "Construire des services utiles, simples et de qualité.",
    innovationDesc: "Créer des solutions digitales adaptées aux réalités des mamans haïtiennes.",
    helpDescription: "Trouvez rapidement des réponses, des démarches et des ressources utiles.",
    searchHelp: "Rechercher dans l'aide...",
    quickHelp: "Aide rapide",
    gettingStarted: "Premiers pas",
    gettingStartedDesc: "Les étapes essentielles pour bien commencer sur Lakou Manman.",
    communityHelpDesc: "Questions sur les groupes, publications et échanges entre mamans.",
    boutiqueHelpDesc: "Tout savoir sur l'achat, la vente, le paiement et la livraison.",
    pediatreHelpDesc: "Aide pour les consultations, rendez-vous et contacts pédiatriques.",
    safetyHelpDesc: "Conseils de sécurité, confidentialité et signalement.",
    toolsHelpDesc: "Aide pour utiliser les outils pratiques de la plateforme.",
    stillNeedHelp: "Besoin d'aide supplémentaire ?",
    supportTeam: "Notre équipe est disponible pour vous orienter.",
    aboutDescription: "Lakou Manman est une communauté digitale pensée pour informer, soutenir et connecter les mamans haïtiennes.",
    ourMission: "Notre mission",
    missionDescription: "Créer un espace digital bienveillant où les mamans haïtiennes peuvent trouver du soutien, des outils utiles et des opportunités concrètes.",
    ourValues: "Nos valeurs",
    activeMoms: "Mamans actives",
    expertPartners: "Partenaires et experts",
    dailyPosts: "Publications quotidiennes",
    satisfaction: "Taux de satisfaction",
    ourTeam: "Notre équipe",
    joinUs: "Rejoignez-nous",
    joinDescription: "Participez à une communauté qui valorise les mamans haïtiennes, leurs besoins et leurs ambitions.",
    getStarted: "Commencer",
    buyerLocation: "Votre localisation",
    buyerLocationPlaceholder: "Ex: Port-au-Prince, Delmas, Pétion-Ville...",
    sellerLocation: "Localisation du vendeur",
    estimatedDistance: "Distance estimée",
    deliveryEstimateUnavailable: "Impossible d'estimer les frais automatiquement avec cette localisation.",
    buyerLocationRequired: "Veuillez choisir votre localisation pour la livraison.",
    
    item: "Article",
    
    // Feed page
    feedTitle: "Fil de la communauté",
    feedDescription: "Partagez, posez des questions et obtenez le soutien des autres mamans.",
    trendingTopics: "Sujets tendances",
    
    // Feed interactions
    searchPlaceholder: "Rechercher une question, un groupe ou un mot-clé...",
    allCities: "Toutes les villes",
    loadingPosts: "Chargement desposts...",
    noPosts: "Aucun post pour le moment. Commencez à partager !",
    city: "Ville",
    
    // Post form
    publishPost: "Publier un post",
    publishPostDesc: "Partagez votre question ou expérience avec la communauté.",
    questionTitle: "Titre de la question ou du sujet",
    category: "Catégorie",
    anonymous: "Anonyme",
    writePost: "Écrire le post...",
    publish: "Publier",
    
    // Post tags
    tagSleep: "Sommeil bébé",
    tagFeeding: "Alimentation",
    tagPostpartum: "Post-partum",
    tagCreole: "Mères dans la diaspora",
    tagWorkKids: "Travail et enfants",
    tagHealth: "Santé",
    tagEducation: "Éducation",
    tagCommunity: "Communauté",
    
    // Auth messages
    connectToPost: "Connectez-vous pour publier un post.",
    
    // Feed sidebar
    dailyQuestion: "Question du jour",
    dailyQuestionDesc: "Une question pour animer la communauté chaque jour.",
    activeGroups: "Groupes actifs",
    
    // Doctor page
    doctorTitle: "Espace Pédiatre",
    doctorDesc: "Contenu validé, questions générales, et informations médicales sérieuses pour les mamans.",
    pediatricAdvice: "Conseils pédiatriques",
    pediatricAdviceDesc: "Contenu validé par des professionnels de santé.",
    validated: "Validé",
    importantNote: "Remarque importante",
    medicalDisclaimer: "Cette section fournit des informations générales uniquement, pas de consultation personnalisée. Pour des urgences médicales ou des questions nécessitant un diagnostic personnel, consultez un service de santé directement.",
    askPediatrician: "Question au pédiatre",
    askPediatricianDesc: "Posez une question générale. Un professionnel y répondra dès que possible.",
    connectToAsk: "Connectez-vous pour poser une question.",
    questionSent: "Question envoyée ! Un professionnel répondra bientôt.",
    questionTopic: "Sujet de la question",
    writeQuestion: "Écrivez votre question générale ici...",
    sendQuestion: "Envoyer la question",
    sending: "Envoi...",
    emergencyNote: "Pour les urgences médicales ou les questions nécessitant un diagnostic personnel, consultez un service de santé directement.",
    
    // Medical tips
    tipFeverTitle: "La fièvre chez le bébé",
    tipFeverText: "Si le bébé a moins de 3 mois et de la fièvre, consultez un médecin rapidement. Pour les autres cas, observez le niveau d'énergie, l'hydratation et la respiration.",
    tipDehydrationTitle: "Signes de déshydratation",
    tipDehydrationText: "Bouche sèche, urines rares et somnolence excessive sont des signes qui nécessitent une attention.",
    tipEmergencyTitle: "Quand appeler le médecin",
    tipEmergencyText: "En cas de difficultés respiratoires, vomissements continus, convulsions ou si le bébé ne réagit pas normalement.",
    
    // Tools page
    toolsTitle: "Outils interactifs",
    toolsDesc: "Quiz, guides, petites expériences utiles qui aident les mamans à s'organiser.",
    sleepQuiz: "Quiz sommeil bébé",
    sleepQuizDesc: "Un outil simple mais très engageant pour évaluer les habitudes de sommeil.",
    seeMyResult: "Voir mon résultat",
    reset: "Réinitialiser",
    allLocations: "Toutes les lieux",
    upcomingTools: "Autres outils à venir",
    upcomingSteps: "Prochaines étapes",
    
    // Upcoming steps list
    upcomingStep1: "• Suivi alimentation et sommeil",
    upcomingStep2: "• Calendrier développement bébé",
    upcomingStep3: "• Checklist bébé interactif",
    upcomingStep4: "• Mini jeux pour enfants",
    
    // Guides page
    guidesTitle: "Guides & ressources",
    guidesDesc: "Des contenus utiles pour vous accompagner pendant la maternité, l'enfance et l'adolescence : PDF, checklists et articles pratiques.",
    download: "Télécharger",
    downloadSoon: "Bientôt disponible",
    premiumContent: "Contenu Premium à venir",
    premiumDesc: "Bientôt, nous aurons des guides avancés, checklist détaillées et ressources exclusives pour les mamans qui veulent aller plus loin. Restez connectés !",
    
    // Individual content types
    Guide: "Guide",
    Article: "Article",
    Checklist: "Checklist",
    PDF: "PDF",
    // Also keep lowercase for compatibility
    guide: "Guide",
    article: "Article",
    checklist: "Checklist",
    pdf: "PDF",
    
    // Quiz questions
    quizQ1: "Combien de fois bébé se réveille-t-il la nuit ?",
    quizQ1Opt1: "0-1 fois",
    quizQ1Opt2: "2-3 fois", 
    quizQ1Opt3: "4 fois ou plus",
    quizQ2: "Bébé a-t-il des routines avant de dormir chaque soir ?",
    quizQ2Opt1: "Oui, presque toujours",
    quizQ2Opt2: "Parfois",
    quizQ2Opt3: "Non",
    quizQ3: "Que fait bébé avant de dormir ?",
    quizQ3Opt1: "Très calme",
    quizQ3Opt2: "Dépend",
    quizQ3Opt3: "Beaucoup d'excitation/écran/bruit",
    
    // Quiz results
    goodSleepBase: "Bonne base de sommeil",
    goodSleepText: "Semble déjà sur une bonne voie. Continuez avec des heures fixes, une lumière tamisée et une routine calme avant de dormir.",
    needsImprovement: "Besoin d'amélioration",
    needsImprovementText: "Quelques ajustements pourraient aider. Essayez une routine plus cohérente et moins de stimulation avant de dormir.",
    needsWork: "Beaucoup de travail à faire",
    needsWorkText: "Considérez une consultation professionnelle. Une routine stricte et un environnement de sommeil optimal sont importants.",
    
    // Tool ideas
    checklistBaby: "Checklist bébé",
    interactiveGuideNewMoms: "Guide interactif pour nouvelles mamans",
    feedingSleepTracking: "Suivi alimentation/sommeil",
    babyDevelopmentCalendar: "Calendrier développement bébé",
    checklistBabyHT: "Checklist sak tibebe",
    interactiveGuideNewMomsHT: "Gid entèraktif pou nouvo manman",
    feedingSleepTrackingHT: "Suivi tétée / dòmi",
    babyDevelopmentCalendarHT: "Kalendriye devlopman tibebe",
    
    // Upcoming features
    feedingSleepTrackingDesc: "Suivi alimentation et sommeil",
    babyDevelopmentCalendarDesc: "Calendrier développement bébé",
    interactiveChecklistBabyDesc: "Checklist bébé interactive",
    miniGamesKidsDesc: "Mini jeux pour enfants",
    
    // Upcoming features - Creole
    feedingSleepTrackingDescHT: "Suivi tétée ak dòmi",
    babyDevelopmentCalendarDescHT: "Kalendri devlopman tibebe",
    interactiveChecklistBabyDescHT: "Checklist sak tibebe entèraktif",
    miniGamesKidsDescHT: "Ti jwèt pou timoun",
    downloadSoon: "Bientôt disponible",
    premiumContent: "Contenu Premium à venir",
    premiumDesc: "Bientôt, nous aurons des guides avancés, checklist détaillées et ressources exclusives pour les mamans qui veulent aller plus loin. Restez connectés !",
    
    // Guide categories
    newMom: "Nouvelle maman",
    practical: "Pratique",
    sleep: "Sommeil",
    feeding: "Alimentation",
    health: "Santé",
    
    // Guide titles
    guideNewMomTitle: "Premiers pas avec bébé",
    guideNewMomDesc: "Un guide pour vous accompagner pendant les trois premiers mois avec bébé et mieux vivre les premiers jours.",
    guideChecklistBabyTitle: "Checklist bébé",
    guideChecklistBabyDesc: "Une liste pratique pour sortir avec bébé sans rien oublier. L'essentiel à garder dans le sac.",
    guideSleepRoutineTitle: "Routine de sommeil de bébé",
    guideSleepRoutineDesc: "Un modèle simple pour installer de bonnes habitudes de sommeil, étape par étape, pour des nuits plus apaisées.",
    guideFeedingTitle: "Alimentation bébé 0-12 mois",
    guideFeedingDesc: "Des repères sur l'alimentation de bébé selon son âge : allaitement, lait infantile et premières purées.",
    guideBathSafetyTitle: "Soins du cordon ombilical",
    guideBathSafetyDesc: "Comment prendre soin du cordon ombilical de bébé jusqu'à sa chute, avec des conseils d'hygiène et de sécurité.",
    guideChildRoutineTitle: "Routines et repères pour les enfants",
    guideChildRoutineDesc: "Des conseils simples pour le sommeil, l'école, l'alimentation, les écrans et l'organisation du quotidien des enfants.",
    guideTeenDialogueTitle: "Mieux accompagner son adolescent",
    guideTeenDialogueDesc: "Des repères pour garder le dialogue, poser un cadre, comprendre les émotions et savoir quand demander de l'aide.",
    featureDoctor: "Accès experts santé",
    featureDoctorDesc: "Consultez des pédiatres et d'autres professionnels qualifiés en ligne ou en personne.",
    step4Title: "Consultez un expert santé",
    step4Desc: "Accédez à des conseils de pédiatres et d'autres professionnels selon vos besoins.",
    
    // Boutique page
    boutiqueTitle: "Boutique",
    boutiqueDesc: "Articles d'occasion pour bébé et maman. Vendez, achetez, ou échangez au sein de la communauté.",
    newest: "Plus récent",
    localOnly: "Uniquement local",
    marketplace: "Place du marché",
    myFavorites: "Mes favoris",
    addToFavorites: "Ajouter aux favoris",
    removeFromFavorites: "Retirer des favoris",
    postFirstItem: "Soyez la première à publier un article !",
    shopSearchPlaceholder: "Rechercher un article ou une boutique...",
    shopClearAll: "Effacer tout",
    shopApplyFilters: "Appliquer les filtres",
    shopResetFilters: "Réinitialiser",
    shopAllLocations: "Tous les lieux",
    shopSellerSourceLabel: "Source vendeur",
    shopSellerSourceAll: "Tous les vendeurs",
    shopSellerSourceIndividual: "Membres de la communauté",
    shopSellerSourceAffiliate: "Magasins affiliés",
    shopPartnerFilterLabel: "Boutique partenaire",
    shopAllPartnerShops: "Toutes les boutiques",
    shopMinPrice: "Prix min",
    shopMaxPrice: "Prix max",
    clearAll: "Effacer tout",
    applyFilters: "Appliquer les filtres",
    reset: "Réinitialiser",
    allLocations: "Tous les lieux",
    noItems: "Aucun article pour le moment",
    loadingItems: "Chargement des articles...",
    startSellingFirstItem: "Vous pouvez commencer à vendre votre premier article !",
    connectToSellOrSeeMore: "Connectez-vous pour vendre des articles ou voir plus.",
    
    // Categories
    vetements: "Vêtements",
    jouets: "Jouets",
    mobilier: "Mobilier",
    livres: "Livres",
    poussettes: "Poussettes & Siège",
    transport: "Transport",
    autres: "Autres",
    
    // Boutique - Quality and Condition
    quality: "Qualité",
    condition: "État",
    new: "Neuf",
    likeNew: "Comme neuf", 
    good: "Bon état",
    used: "Usé",
    
    // Boutique - Actions
    add: "Ajouter",
    sell: "Vendre",
    buy: "Acheter",
    exchange: "Échanger",
    cancel: "Annuler",
    publish: "Publier",
    
    // Form labels
    itemName: "Nom de l'article",
    itemDescription: "Description",
    price: "Prix",
    location: "Localisation",
    contactInfo: "Contact (téléphone ou WhatsApp)",
    images: "Images (optionnel)",
    contactToSeller: "Contacter le vendeur",
    conversationError: "Erreur lors de la création de la conversation. Veuillez réessayer.",
    messageUser: "Message",
    viewProfile: "Voir le profil",
    contactMember: "Contacter le membre",
    sendMessage: "Envoyer un message",
    userProfile: "Profil de l'utilisateur",
    memberSince: "Membre depuis",
    noBio: "Aucune biographie",
    contact: "Contacter",
    activeMembers: "Membres actifs",
    viewAllMembers: "Voir tous les membres",
    buyNow: "Acheter maintenant",
    securePayment: "Paiement sécurisé",
    paymentProcessing: "Traitement du paiement",
    paymentInfo: "Les informations de paiement sont cryptées et sécurisées",
    confirmPayment: "Confirmer le paiement",
    paymentSuccessful: "Paiement réussi",
    thankYouForPurchase: "Merci pour votre achat !",
    processingPayment: "Traitement en cours...",
    payNow: "Payer maintenant",
    continueShopping: "Continuer vos achats",
    backToHome: "Retour à l'accueil",
    transactionId: "ID de transaction",
    createAccountForOrders: "Créez un compte pour suivre vos commandes",
    stripeNotConfigured: "Mode démo - Stripe n'est pas encore configuré",
    item: "Article",
    boutiqueItem: "Article de la boutique",
    
    // Form placeholders
    itemExample: "Ex: Poussette bébé, Vêtements 6 mois...",
    priceExample: "Ex: 500",
    descriptionExample: "Décrivez l'article — taille, couleur, état, etc...",
    locationExample: "Ex: Port-au-Prince, Delmas...",
    contactExample: "Ex: +509 3456 7890",
    
    // Image upload
    maxImagesAlert: "Vous pouvez ajouter un maximum de {{maxImages}} images.",
    imageTypeAlert: "Seules les images sont acceptées (JPG, PNG, WEBP).",
    imageSizeAlert: "L'image est trop volumineuse (maximum 5MB).",
    uploadError: "Erreur lors du téléchargement de l'image.",
    uploadingImages: "Téléchargement des images...",
    dragDropImages: "Glissez les images ici ou",
    chooseFiles: "Choisir les fichiers",
    imageFormats: "JPG, PNG, WEBP • Maximum 5MB • Maximum {{maxImages}} images",
    addAnotherImage: "Ajouter une autre image",
    maxVideosAlert: "Vous pouvez ajouter un maximum de {{maxVideos}} vidéo.",
    videoTypeAlert: "Seules les vidéos sont acceptées (MP4, WEBM, MOV).",
    videoSizeAlert: "La vidéo est trop volumineuse (maximum 25MB).",
    videoUploadError: "Erreur lors du téléchargement de la vidéo.",
    uploadingVideos: "Téléchargement de la vidéo...",
    dragDropVideos: "Glissez la vidéo ici ou",
    videoFormats: "MP4, WEBM, MOV • Maximum 25MB • Maximum {{maxVideos}} vidéo",
    addAnotherVideo: "Ajouter une autre vidéo",
    gamesTitle: "Jeux et détente",
    gamesDesc: "Une petite rubrique pour s'amuser, faire une pause et partager un moment avec les enfants.",
    gamesMemoryTitle: "Mémoire express",
    gamesMemoryDesc: "Retrouvez les paires le plus vite possible.",
    gamesMemoryMoves: "Coups",
    gamesMemoryWin: "Bravo ! Vous avez retrouvé toutes les paires.",
    gamesEmotionTitle: "Cartes émotions",
    gamesEmotionDesc: "Choisissez l'émotion qui correspond le mieux à chaque petite situation.",
    gamesEmotionProgress: "Progression",
    gamesEmotionScore: "Score émotions",
    gamesEmotionCorrect: "Bien vu ! Cette émotion correspond à la situation.",
    gamesEmotionWrong: "Pas tout à fait. Regardez l'indice et essayez la suivante.",
    gamesEmotionCompleted: "Bravo ! Vous avez terminé les cartes émotions.",
    gamesEmotionPlayAgain: "Rejouer",
    gamesEmotionNext: "Carte suivante",
    gamesEmotionTipLabel: "Astuce douceur",
    gamesEmotionOptionJoy: "Joie",
    gamesEmotionOptionTired: "Fatigue",
    gamesEmotionOptionFrustrated: "Frustration",
    gamesEmotionOptionSad: "Tristesse",
    gamesEmotionScenarioOne: "Le doudou préféré est introuvable juste avant de dormir.",
    gamesEmotionScenarioTwo: "Après une longue journée, l'enfant bâille et frotte ses yeux.",
    gamesEmotionScenarioThree: "La tour de blocs tombe juste après avoir été construite.",
    gamesEmotionScenarioFour: "L'enfant court montrer son dessin avec un grand sourire.",
    gamesEmotionTipOne: "Nommer l'émotion et rassurer doucement aide l'enfant à se sentir compris.",
    gamesEmotionTipTwo: "Quand l'enfant est fatigué, une voix douce et une ambiance calme l'aident à se poser.",
    gamesEmotionTipThree: "Accueillir la frustration et proposer de recommencer ensemble aide à reprendre confiance.",
    gamesEmotionTipFour: "Partager la joie et féliciter l'effort renforce la confiance de l'enfant.",
    gamesRoutineTitle: "Routine douceur",
    gamesRoutineDesc: "Remettez dans l'ordre une petite routine apaisante pour le soir.",
    gamesRoutineHint: "Touchez les étapes dans le bon ordre.",
    gamesRoutineSuccess: "Bravo ! Cette routine est bien organisée pour un moment calme.",
    gamesRoutineRetry: "Pas encore. Reprenez tranquillement depuis le début.",
    gamesRoutineProgress: "Étapes",
    gamesRoutineStepOne: "Ranger les jouets",
    gamesRoutineStepTwo: "Prendre un bain",
    gamesRoutineStepThree: "Lire une histoire",
    gamesRoutineStepFour: "Faire un câlin et dormir",
    gamesGuessTitle: "Devine le nombre",
    gamesGuessDesc: "Trouvez le nombre mystère entre 1 et 20.",
    gamesGuessPlaceholder: "Entrez un nombre entre 1 et 20",
    gamesGuessAction: "Deviner",
    gamesGuessHint: "Commencez avec votre première proposition.",
    gamesGuessRange: "Choisissez un nombre valide entre 1 et 20.",
    gamesGuessWin: "Bravo ! Vous avez trouvé le bon nombre.",
    gamesGuessLow: "C'est plus grand. Essayez encore.",
    gamesGuessHigh: "C'est plus petit. Essayez encore.",
    gamesAttempts: "Essais",
    gamesReset: "Recommencer",
    gamesFamilyTitle: "Des jeux simples pour souffler un peu",
    gamesFamilyDesc: "Cette première rubrique Jeux est pensée pour offrir un moment léger aux mamans et aux enfants. D'autres activités pourront être ajoutées ensuite.",
    gamesHeroBadge: "Pause ludique",
    gamesStatsAvailable: "Jeux disponibles",
    gamesStatsMemory: "Paires trouvées",
    gamesStatsEmotion: "Émotions",
    gamesStatsRoutine: "Routine",
    gamesStatsGuess: "Tentatives",
    gamesStatsQuiz: "Score quiz",
    gamesMemoryPairs: "Paires",
    gamesGuessRangeLabel: "Intervalle",
    gamesQuizTitle: "Mini quiz famille",
    gamesQuizDesc: "Trois petites questions rapides pour jouer ensemble.",
    gamesQuizProgress: "Progression",
    gamesQuizScore: "Score",
    gamesQuizNext: "Question suivante",
    gamesQuizFinish: "Voir le résultat",
    gamesQuizRestart: "Relancer le quiz",
    gamesQuizCorrect: "Bonne réponse !",
    gamesQuizWrong: "Pas tout à fait, mais on continue.",
    gamesQuizCompleted: "Quiz terminé !",
    gamesQuizPlayAgain: "Rejouer",
    gamesCornerTitle: "Un coin détente pensé pour la famille",
    gamesCornerDesc: "Des activités courtes, simples et rassurantes pour créer un petit moment de complicité.",
    gamesCornerTipOne: "Privilégiez des sessions courtes de 5 minutes.",
    gamesCornerTipTwo: "Jouez ensemble pour valoriser chaque progrès.",
    gamesCornerTipThree: "Alternez jeu, respiration et compliments.",
    gamesQuizQuestionOne: "Quel type d'activité aide un enfant à se calmer avant de dormir ?",
    gamesQuizQuestionOneOptionOne: "Un petit rituel doux",
    gamesQuizQuestionOneOptionTwo: "Un écran très lumineux",
    gamesQuizQuestionOneOptionThree: "Beaucoup de bruit",
    gamesQuizQuestionTwo: "Quel jeu aide particulièrement la mémoire ?",
    gamesQuizQuestionTwoOptionOne: "Retrouver des paires",
    gamesQuizQuestionTwoOptionTwo: "Courir sans pause",
    gamesQuizQuestionTwoOptionThree: "Faire beaucoup de bruit",
    gamesQuizQuestionThree: "Quand un enfant réussit, la meilleure réaction est de...",
    gamesQuizQuestionThreeOptionOne: "Le féliciter",
    gamesQuizQuestionThreeOptionTwo: "Ne rien dire",
    gamesQuizQuestionThreeOptionThree: "Changer tout de suite de sujet",
    
    // Messages page
    loginToSeeMessages: "Connectez-vous pour voir vos messages",
    loginToSeeMessagesDesc: "Inscrivez-vous ou connectez-vous pour accéder à vos messages.",
    loadingConversations: "Chargement des conversations...",
    today: "Aujourd'hui",
    yesterday: "Hier",
    noMessages: "Aucun message",
    user: "Utilisateur",
    conversation: "conversation",
    noMessagesInChat: "Aucun message dans cette conversation",
    sendFirstMessage: "Envoyez le premier message !",
    selectConversation: "Sélectionnez une conversation",
    selectConversationDesc: "Sélectionnez une conversation dans la liste à gauche pour commencer à discuter.",
    
    // Admin page
    loadingAdminPanel: "Chargement du panel admin...",
    adminPanel: "Panel Admin",
    adminPanelDesc: "Gérer le contenu, modérer les posts, et surveiller la communauté.",
    reportedPosts: "Posts signalés",
    userList: "Utilisateurs",
    userListDesc: "Liste de tous les utilisateurs de la plateforme.",
    anonymous: "Anonyme",
    hidden: "Masqué",
    reported: "Signalé",
    withoutName: "Sans nom",
    openReports: "Rapports ouverts",
    noOpenReports: "Aucun rapport ouvert.",
    hide: "Masquer",
    show: "Montrer",
    postId: "ID du post :",
    reason: "Raison :",
    users: "Utilisateurs",
    totalPosts: "Total des posts",
    reports: "Rapports",
    allPosts: "Tous les posts",
    noReportedPosts: "Aucun post signalé pour le moment.",
    anonymous: "Anonyme",
    reported: "Signalé",
    
    // Notifications page
    loginToSeeNotifications: "Connectez-vous pour voir vos notifications",
    loginToSeeNotificationsDesc: "Inscrivez-vous ou connectez-vous pour accéder à vos notifications.",
    notifications: "Notifications",
    unread: "non lu",
    markAllAsRead: "Marquer tout comme lu",
    clearAll: "Tout effacer",
    noNotifications: "Aucune notification",
    noNotificationsDesc: "Vous recevrez des notifications lorsque d'autres utilisateurs vous enverront des messages ou aimeront vos articles.",
    justNow: "À l'instant",
    minutesAgo: "minutes",
    hoursAgo: "heures",
    daysAgo: "jours",
    view: "Voir",
    
    // Favorites page
    loginToSeeFavorites: "Connectez-vous pour voir vos favoris",
    loginToSeeFavoritesDesc: "Inscrivez-vous ou connectez-vous pour accéder à vos articles favoris.",
    myFavorites: "Mes Favoris",
    returnToShop: "Retourner à la boutique",
    noFavorites: "Vous n'avez aucun favori",
    noFavoritesDesc: "Ajoutez des articles à vos favoris pour les retrouver rapidement ici.",
    discoverShop: "Découvrir la boutique",
    item: "article",
    liked: "aimé",
    viewDetails: "Voir les détails",
    
    // Profile page
    loadingProfile: "Chargement du profil...",
    myProfile: "Mon Profil",
    profileDesc: "Gérez les informations de votre profil.",
    uploadingPhoto: "Téléchargement de la photo...",
    newMom: "Nouvelle maman",
    editProfile: "Modifier le profil",
    editProfileDesc: "Modifiez vos informations pour que la communauté puisse vous voir.",
    profileUpdated: "Profil mis à jour !",
    nameOrPseudo: "Nom ou pseudo",
    city: "Ville",
    country: "Pays",
    childrenAges: "Repères d'âge utiles (facultatif)",
    childrenAgesExample: "Ex: 6 mois, 3 ans, enfance",
    bio: "Bio",
    bioPlaceholder: "Racontez un peu sur vous-même...",
    save: "Enregistrer",
    saving: "Enregistrement",
    
    // Registration and Login pages
    password: "Mot de passe",
    createAccount: "Créer votre compte",
    joinCommunity: "Rejoignez Lakou Manman et personnalisez votre expérience en douceur",
    passwordsNotMatch: "Les mots de passe ne correspondent pas.",
    passwordMinLength: "Le mot de passe doit contenir au moins 6 caractères.",
    emailAlreadyInUse: "Cet email est déjà utilisé.",
    passwordTooWeak: "Le mot de passe est trop faible.",
    emailRequired: "Une adresse email est obligatoire.",
    nameRequired: "Un nom ou pseudo est obligatoire.",
    genericError: "Une erreur s'est produite. Essayez à nouveau.",
    googleAccountEmailRequired: "Le compte Google doit fournir une adresse email.",
    googleSignInNotEnabled: "La connexion Google n'est pas encore activée sur Firebase.",
    googleSignInFailed: "Impossible de continuer avec Google pour le moment.",
    networkError: "Problème de connexion internet. Vérifiez votre réseau puis réessayez.",
    nameExample: "Ex: Michaëlle",
    emailExample: "bonjour@example.com",
    passwordPlaceholder: "Au moins 6 caractères",
    confirmPassword: "Confirmer le mot de passe",
    confirmPasswordPlaceholder: "Le même mot de passe",
    cityExample: "Ex: Montréal",
    countryExample: "Ex: Canada",
    creatingAccount: "Création du compte",
    createMyAccount: "Créer mon compte",
    alreadyHaveAccount: "Vous avez déjà un compte ?",
    welcomeBack: "Bon retour",
    loginToAccount: "Connectez-vous à votre compte Lakou Manman",
    forgotPassword: "Mot de passe oublié ?",
    loggingIn: "Connexion",
    noAccount: "Vous n'avez pas de compte ?",
    continueWithGoogle: "Continuer avec Google",
    createAccountWithGoogle: "Créer un compte avec Google",
    orContinueWithEmail: "ou continuez avec votre email",
    
    // Theme page
    changeTheme: "Changer la couleur de fond",
    chooseTheme: "Choisir la couleur de fond",
    rosePale: "Rose pâle",
    grenadinFonce: "Grenadin foncé",
    peche: "Pêche",
    bleFonce: "Bleu foncé",
    cielBleu: "Ciel bleu",
    orange: "Orange",
    soleil: "Soleil",
    
    // Groups page
    groupsTitle: "Groupes de soutien",
    groupsDescription: "Petites communautés thématiques pour créer plus de liens et discussions approfondies.",
    joiningGroup: "Rejoindre...",
    joinGroup: "Rejoindre le groupe",
    alreadyMember: "Déjà membre",
    activeGroups: "Groupes actifs",
    discoverGroups: "Groupes à rejoindre",
    noActiveGroups: "Vous ne faites partie d'aucun groupe pour le moment.",
    noDiscoverGroups: "Vous avez déjà rejoint tous les groupes disponibles.",
    signInToJoinGroups: "Connectez-vous pour rejoindre un groupe.",
    members: "membres",
    posts: "posts",
    seePosts: "Voir les posts",
    
    // Group names
    groupNewborn: "Naissance & nouveau-né",
    groupNewbornDesc: "Espace pour questions et repères autour des premières semaines de vie.",
    groupChildren: "Enfance",
    groupChildrenDesc: "Échanges sur la santé, l'école, le développement, les routines et le quotidien des enfants.",
    groupTeens: "Adolescence",
    groupTeensDesc: "Un espace pour parler d'école, d'émotions, de dialogue, de limites et de bien-être à l'adolescence.",
    groupPostpartum: "Post-partum", 
    groupPostpartumDesc: "Soutien après l'accouchement : corps, émotions, récupération et adaptation.",
    groupDiaspora: "Diaspora",
    groupDiasporaDesc: "Connectez-vous avec la communauté haïtienne du monde entier.",
    groupFeeding: "Alimentation",
    groupFeedingDesc: "Conseils sur l'alimentation, l'allaitement et la nutrition au quotidien.",
    groupWorkFamily: "Travail & famille",
    groupWorkFamilyDesc: "Équilibre entre travail, charge mentale et vie familiale.",
    groupAutismParents: "Parents d'enfants autistes",
    groupAutismParentsDesc: "Un espace de soutien, de ressources et de partage pour les parents qui accompagnent un enfant autiste au quotidien.",
    groupGriefLoss: "Deuil et perte",
    groupGriefLossDesc: "Un espace sensible et bienveillant pour trouver écoute, soutien et réconfort face à une perte.",
    groupDefaultDescription: "Espace pour questions, expériences et soutien entre membres.",
    loadingGroup: "Chargement du groupe",
    noPostsInGroup: "Aucun post dans ce groupe pour le moment. Commencez à partager !",
    groupInformation: "Informations du groupe",
    leaveGroup: "Quitter le groupe",
    leavingGroup: "Quitter...",
    inviteMembers: "Inviter des membres",
    copyInviteLink: "Copier le lien d'invitation",
    inviteLinkCopied: "Lien d'invitation copié",
    inviteLinkCopyError: "Impossible de copier le lien pour le moment",
    pinnedPosts: "Posts épinglés",
    noPinnedPosts: "Aucun post épinglé pour le moment.",
    noMembersYet: "Aucun membre pour le moment.",
    openingConversation: "Ouverture...",
    viewLessMembers: "Voir moins de membres",
    groupRules: "Règles du groupe",
    groupRuleRespect: "Respectez chaque personne, chaque parcours et chaque opinion.",
    groupRuleKindness: "Gardez un ton bienveillant et évitez les attaques personnelles.",
    groupRulePrivacy: "Ne partagez pas les informations privées des membres hors du groupe.",
    groupRuleMedical: "Les conseils médicaux urgents doivent toujours être confirmés par un professionnel de santé.",
    mothers: "mères",
    discussions: "discussions",
  },
  ht: {
    // Navigation
    home: "Akèy",
    feed: "Kominote",
    writeComment: "Ekri yon kòmantè...",
    report: "Repote",
    confirmReport: "Ou vle rapòte pòs sa a?",
    groups: "Gwoup",
    doctor: "Pedyat",
    pediatre: "Pedyatri",
    healthHub: "Espas lasante",
    gynecology: "Jinekoloji",
    psychology: "Sikoloji",
    tools: "Zouti",
    guides: "Gid",
    games: "Jwèt",
    boutique: "Boutik",
    messages: "Mesaj",
    favorites: "Favori",
    notifications: "Notifikasyon",
    profile: "Pwofil",
    login: "Konekte",
    register: "Enskri",
    logout: "Dekonekte",
    
    // Site texts
    title: "Lakou Manman — Kominote manman ayisyèn",
    description: "Yon platfòm entèraktif pou manman ayisyèn jwenn konsèy, sipò, epi pataje eksperyans yo.",
    welcomeBanner: "Byenvi nan Lakou Manman — Kominote manman ayisyèn toupatou nan mond lan",
    aboutTitle: "Apwou de Lakou Manman",
    mission: "Kominote manman ayisyèn toupatou nan mond lan pou pataje, aprann, epi sipòte youn lòt.",
    siteDescription: "Yon platfòm entèraktif pou manman ayisyèn jwenn konsèy, sipò, epi pataje eksperyans yo ak kominote, resous pratik, kontni validé, ak yon vizyon pou tounen yon vrè rezo sosyal pou manman.",
    
    // Home page features
    communityTitle: "Kominote aktif",
    communityDesc: "Poze kestyon, pataje eksperyans ou, epi jwenn sipò nan men lòt manman ayisyèn.",
    supportGroupsTitle: "Gwoup sipò",
    supportGroupsDesc: "Rejwenn gwoup tematik pou diskite sou defi espesifik ak jwenn konsey ekspe.",
    pediatricAdviceTitle: "Konsèy pedyat",
    pediatricAdviceDesc: "Jwenn rekomandasyon pou medeyen ak klinik pou byenfè timal bebe ou.",
    educationalResourcesTitle: "Resous edikatif",
    educationalResourcesDesc: "Jwenn aksè ak liv, gid ak atik sou lasante manman ak ti bebe.",
    practicalToolsTitle: "Zouti pratik",
    practicalToolsDesc: "Kalkilatris dat akouchman manman, suivi manje, ak lòt zouti itil.",
    localResourcesTitle: "Resous lokal",
    localResourcesDesc: "Jwenn enfòmasyon sou sèvis manman ak ti bebe tou prèw.",
    
    // Boutique
    boutiqueTitle: "Boutik",
    boutiqueDesc: "Atik d'okazyon pou bebe ak manman. Vann, achte, oswa echanje nan kominote a.",
    sellItem: "Vann yon atik",
    searchPlaceholder: "Chèche yon atik...",
    filters: "Filtr",
    allCategories: "Tout kategori yo",
    allConditions: "Tout kondisyon yo",
    price: "Pri",
    location: "Lokasyon",
    condition: "Kondisyon",
    new: "Nèf",
    likeNew: "Tankou nèf",
    good: "Bon eta",
    used: "Itilize",
    contact: "Kontakte",
    contactToSeller: "Kontakte vandè",
    conversationError: "Erè pandan kreyasyon konvèsasyon an. Reesaye.",
    messageUser: "Mesaje",
    viewProfile: "Gade pwofil la",
    contactMember: "Kontakte manm lan",
    sendMessage: "Voye mesaj",
    userProfile: "Pwofil itilizatè a",
    memberSince: "Manm depi",
    noBio: "Pa gen biyografi",
    contact: "Kontakte",
    activeMembers: "Manm aktif",
    viewAllMembers: "Gade tout manm yo",
    buyNow: "Achte kounye a",
    securePayment: "Pèman sekirize",
    paymentProcessing: "Trajman pèman an",
    paymentInfo: "Enfòmasyon pèman yo kripte ak sekirize",
    confirmPayment: "Konfime pèman an",
    paymentSuccessful: "Pèman reyisi",
    thankYouForPurchase: "Mèsi pou acha ou !",
    processingPayment: "Ap trajte...",
    payNow: "Peye kounye a",
    continueShopping: "Kontinye achte",
    backToHome: "Retounen nan akèy",
    transactionId: "ID transaksyon",
    createAccountForOrders: "Kreye yon kont pou swiv lòd ou yo",
    stripeNotConfigured: "Mod demo - Stripe pa konfigire ankò",
    item: "Atik",
    boutiqueItem: "Atik boutik la",
    addToFavorites: "Ajoute nan favori",
    removeFromFavorites: "Retire nan favori",
    noItems: "Pa gen atik pou kounye a",
    loadingItems: "Ap chaje atik yo...",
    startSellingFirstItem: "Ou ka kòmanse vann premye atik ou a!",
    connectToSellOrSeeMore: "Konekte pou vann atik oswa wè plis.",
    postFirstItem: "Dwe premye moun ki pibliye yon atik !",
    shopSearchPlaceholder: "Chèche yon atik oswa yon boutik...",
    shopClearAll: "Efase tout",
    shopApplyFilters: "Aplike filtre yo",
    shopResetFilters: "Reyinisyalize",
    shopAllLocations: "Tout kote",
    shopSellerSourceLabel: "Kalite vandè",
    shopSellerSourceAll: "Tout vandè",
    shopSellerSourceIndividual: "Manm kominote",
    shopSellerSourceAffiliate: "Magazen afilye",
    shopPartnerFilterLabel: "Boutik patnè",
    shopAllPartnerShops: "Tout boutik yo",
    shopMinPrice: "Pri min",
    shopMaxPrice: "Pri maksimòm",
    clearAll: "efase tout",
    applyFilters: "Applike filtre yo",
    reset: "Reyinisye",
    allLocations: "Tout kote",
    
    // Categories
    vetements: "Rad",
    jouets: "Jwèt",
    mobilier: "Mèb",
    livres: "Liv",
    poussettes: "Pousèt & chèz tibebe",
    transport: "Transpò",
    autres: "Lòt",
    
    // Boutique - Quality and Condition
    quality: "Kalite",
    condition: "Eta",
    new: "Nèf",
    likeNew: "Tankou nèf",
    good: "Bon eta",
    used: "Itilize",
    
    // Boutique - Actions
    sell: "Vann",
    buy: "Achte",
    exchange: "Echanje",
    
    // Form labels
    itemName: "Non atik la",
    itemDescription: "Deskripsyon",
    price: "Pri",
    location: "Lokalizasyon",
    contactInfo: "Kontak (telefòn oswa WhatsApp)",
    images: "Imaj (opsyonèl)",
    
    // Form placeholders
    itemExample: "Ex: Pousèt tibebe, Rad 6 mwa...",
    priceExample: "Ex: 500",
    descriptionExample: "Dekri atik la — tay, koulè, eta, elatriye...",
    locationExample: "Ex: Pòtoprens, Delma...",
    contactExample: "Ex: +509 3456 7890",
    
    // Image upload
    maxImagesAlert: "Ou ka ajoute maksimòm {{maxImages}} imaj.",
    imageTypeAlert: "Seules les images sont acceptées (JPG, PNG, WEBP).",
    imageSizeAlert: "Imaj la twò gran (maksimòm 5MB).",
    uploadError: "Erè pandan upload imaj la.",
    uploadingImages: "Ap chaje imaj yo...",
    dragDropImages: "Glisye imaj yo isit la oswa",
    chooseFiles: "Chwazi fichye yo",
    imageFormats: "JPG, PNG, WEBP • Maksimòm 5MB • Maksimòm {{maxImages}} imaj",
    addAnotherImage: "Ajoute yon lòt imaj",
    maxVideosAlert: "Ou ka ajoute maksimòm {{maxVideos}} videyo.",
    videoTypeAlert: "Se sèlman videyo yo aksepte (MP4, WEBM, MOV).",
    videoSizeAlert: "Videyo a twò lou (maksimòm 25MB).",
    videoUploadError: "Erè pandan upload videyo a.",
    uploadingVideos: "Ap chaje videyo a...",
    dragDropVideos: "Glisye videyo a isit la oswa",
    videoFormats: "MP4, WEBM, MOV • Maksimòm 25MB • Maksimòm {{maxVideos}} videyo",
    addAnotherVideo: "Ajoute yon lòt videyo",
    gamesTitle: "Jwèt ak detant",
    gamesDesc: "Yon ti seksyon pou pran plezi, fè yon poz, epi pase yon moman ak timoun yo.",
    gamesMemoryTitle: "Memwa rapid",
    gamesMemoryDesc: "Retwouve pè yo pi vit ou kapab.",
    gamesMemoryMoves: "Kout",
    gamesMemoryWin: "Bravo ! Ou jwenn tout pè yo.",
    gamesEmotionTitle: "Kat emosyon",
    gamesEmotionDesc: "Chwazi emosyon ki pi byen mache ak chak ti sitiyasyon.",
    gamesEmotionProgress: "Pwogrè",
    gamesEmotionScore: "Nòt emosyon",
    gamesEmotionCorrect: "Byen wè ! Emosyon sa a mache ak sitiyasyon an.",
    gamesEmotionWrong: "Pa fin sa. Gade endis la epi eseye pwochen an.",
    gamesEmotionCompleted: "Bravo ! Ou fini ak kat emosyon yo.",
    gamesEmotionPlayAgain: "Rejwe",
    gamesEmotionNext: "Pwochen kat",
    gamesEmotionTipLabel: "Ti konsèy dous",
    gamesEmotionOptionJoy: "Kè kontan",
    gamesEmotionOptionTired: "Fatig",
    gamesEmotionOptionFrustrated: "Fristrasyon",
    gamesEmotionOptionSad: "Tristès",
    gamesEmotionScenarioOne: "Ti nounous prefere a pa jwenn jis anvan dòmi.",
    gamesEmotionScenarioTwo: "Apre yon long jounen, timoun nan ap bay baye epi fwote je l.",
    gamesEmotionScenarioThree: "Gwo tou blòk la tonbe jis apre li te fin konstwi l.",
    gamesEmotionScenarioFour: "Timoun nan ap kouri montre desen li ak yon gwo souri.",
    gamesEmotionTipOne: "Bay emosyon an non li epi rassire dousman ede timoun nan santi yo konprann li.",
    gamesEmotionTipTwo: "Lè timoun nan fatige, yon vwa dous ak yon anviwònman kalm ede l poze.",
    gamesEmotionTipThree: "Akeyi fristrasyon an epi pwopoze rekòmanse ansanm ede l reprann konfyans.",
    gamesEmotionTipFour: "Pataje kè kontan an epi felisite efò a ranfòse konfyans timoun nan.",
    gamesRoutineTitle: "Woutin dous",
    gamesRoutineDesc: "Mete ti etap yo nan bon lòd pou yon fen jounen ki kalm.",
    gamesRoutineHint: "Peze etap yo nan bon lòd.",
    gamesRoutineSuccess: "Bravo ! Woutin sa a byen òganize pou yon moman kalm.",
    gamesRoutineRetry: "Pa ko sa. Rekòmanse dousman depi nan kòmansman.",
    gamesRoutineProgress: "Etap",
    gamesRoutineStepOne: "Ranje jwèt yo",
    gamesRoutineStepTwo: "Pran benyen",
    gamesRoutineStepThree: "Li yon istwa",
    gamesRoutineStepFour: "Fè yon akolad epi dòmi",
    gamesGuessTitle: "Devine nimewo a",
    gamesGuessDesc: "Jwenn nimewo mistè a ant 1 ak 20.",
    gamesGuessPlaceholder: "Antre yon nimewo ant 1 ak 20",
    gamesGuessAction: "Devine",
    gamesGuessHint: "Kòmanse ak premye esè ou.",
    gamesGuessRange: "Chwazi yon nimewo valab ant 1 ak 20.",
    gamesGuessWin: "Bravo ! Ou jwenn bon nimewo a.",
    gamesGuessLow: "Li pi gwo. Eseye ankò.",
    gamesGuessHigh: "Li pi piti. Eseye ankò.",
    gamesAttempts: "Esè",
    gamesReset: "Rekòmanse",
    gamesFamilyTitle: "Jwèt senp pou pran yon ti souf",
    gamesFamilyDesc: "Premye seksyon Jwèt sa a fèt pou ofri yon ti moman lejè pou manman ak timoun yo. N ap ka ajoute lòt aktivite apre sa.",
    gamesHeroBadge: "Ti moman plezi",
    gamesStatsAvailable: "Jwèt ki la",
    gamesStatsMemory: "Pè jwenn",
    gamesStatsEmotion: "Emosyon",
    gamesStatsRoutine: "Woutin",
    gamesStatsGuess: "Ese",
    gamesStatsQuiz: "Nòt quiz la",
    gamesMemoryPairs: "Pè",
    gamesGuessRangeLabel: "Entèval",
    gamesQuizTitle: "Ti quiz fanmi",
    gamesQuizDesc: "Twa ti kestyon rapid pou jwe ansanm.",
    gamesQuizProgress: "Pwogrè",
    gamesQuizScore: "Nòt",
    gamesQuizNext: "Pwochen kestyon",
    gamesQuizFinish: "Gade rezilta a",
    gamesQuizRestart: "Relanse quiz la",
    gamesQuizCorrect: "Bon repons !",
    gamesQuizWrong: "Li pa t sa, men ann kontinye.",
    gamesQuizCompleted: "Quiz la fini !",
    gamesQuizPlayAgain: "Rejwe",
    gamesCornerTitle: "Yon ti kwen detant pou fanmi an",
    gamesCornerDesc: "Aktivite kout, senp ak dou pou kreye yon bèl ti moman ansanm.",
    gamesCornerTipOne: "Chwazi ti sesyon 5 minit sèlman.",
    gamesCornerTipTwo: "Jwe ansanm pou ankouraje chak pwogrè.",
    gamesCornerTipThree: "Mete jwèt, respirasyon ak konpliman ansanm.",
    gamesQuizQuestionOne: "Ki kalite aktivite ki ede yon timoun kalme anvan dòmi?",
    gamesQuizQuestionOneOptionOne: "Yon ti rit dous",
    gamesQuizQuestionOneOptionTwo: "Yon ekran byen klere",
    gamesQuizQuestionOneOptionThree: "Anpil bri",
    gamesQuizQuestionTwo: "Ki jwèt ki ede memwa travay pi byen?",
    gamesQuizQuestionTwoOptionOne: "Chèche menm pè yo",
    gamesQuizQuestionTwoOptionTwo: "Kouri san rete",
    gamesQuizQuestionTwoOptionThree: "Fè gwo bri",
    gamesQuizQuestionThree: "Lè yon timoun reyisi, ki sa ki pi bon pou fè?",
    gamesQuizQuestionThreeOptionOne: "Felisite li",
    gamesQuizQuestionThreeOptionTwo: "Pa di anyen",
    gamesQuizQuestionThreeOptionThree: "Chanje sijè a tousuit",
    
    // Messages page
    loginToSeeMessages: "Konekte ou pou wè mesaj yo",
    loginToSeeMessagesDesc: "Enskri oswa konekte pou aksede nan mesaj ou yo.",
    loadingConversations: "Ap chaje konvèsasyon yo...",
    today: "Jodi a",
    yesterday: "Yè",
    noMessages: "Pa gen mesaj",
    user: "Itilizatè",
    conversation: "konvèsasyon",
    noMessagesInChat: "Pa gen mesaj nan konvèsasyon sa",
    sendFirstMessage: "Voye premye mesaj ou !",
    selectConversation: "Chwazi yon konvèsasyon",
    selectConversationDesc: "Chwazi yon konvèsasyon nan lis la a goch pou kòmanse voye mesaj.",
    
    // Admin page
    loadingAdminPanel: "Ap chaje panel admin...",
    adminPanel: "Panel Admin",
    adminPanelDesc: "Jere kontni, modere pòs, ak siveye kominote a.",
    reportedPosts: "Pòs rapòte",
    userList: "Itilizatè",
    userListDesc: "Lis tout itilizatè nan platfòm nan.",
    anonymous: "Anonim",
    hidden: "Kache",
    reported: "Rapòte",
    withoutName: "San non",
    openReports: "Rapò ouvè",
    noOpenReports: "Pa gen rapò ouvè.",
    hide: "Kache",
    show: "Montre",
    postId: "ID pòs :",
    reason: "Rezon :",
    users: "Itilizatè",
    totalPosts: "Total pòs",
    reports: "Rapò",
    allPosts: "Tout pòs",
    noReportedPosts: "Pa gen pòs rapòte pou kounye a.",
    anonymous: "Anonim",
    reported: "Rapòte",
    
    // Notifications page
    loginToSeeNotifications: "Konekte ou pou wè notifikasyon ou yo",
    loginToSeeNotificationsDesc: "Enskri oswa konekte pou aksede nan notifikasyon ou yo.",
    notifications: "Notifikasyon",
    unread: "pa li",
    markAllAsRead: "Make tout kòm li",
    clearAll: "Efase tout",
    noNotifications: "Pa gen notifikasyon",
    noNotificationsDesc: "Ou pral resevwa notifikasyon lè lòt itilizatè voye mesaj pou ou oswa renmen atik ou yo.",
    justNow: "Lontan",
    minutesAgo: "min",
    hoursAgo: "h",
    daysAgo: "j",
    view: "Wè",
    
    // Favorites page
    loginToSeeFavorites: "Konekte ou pou wè favori ou yo",
    loginToSeeFavoritesDesc: "Enskri oswa konekte pou aksede nan atik ou pi renmen yo.",
    myFavorites: "Favori Mwen",
    returnToShop: "Retounen boutik la",
    noFavorites: "Ou pa gen favori ankò",
    noFavoritesDesc: "Ajoute atik nan favori ou yo pou jwenn yo rapidman isit la.",
    discoverShop: "Dekouvri boutik la",
    item: "atik",
    liked: "amye",
    viewDetails: "Wè detay",
    
    // Profile page
    loadingProfile: "Ap chaje pwofil...",
    myProfile: "Pwofil Mwen",
    profileDesc: "Jere enfòmasyon pwofil ou.",
    uploadingPhoto: "Ap telechaje foto...",
    newMom: "Nouvo manman",
    editProfile: "Edite pwofil",
    editProfileDesc: "Modifye enfòmasyon ou pou kominote a wè.",
    profileUpdated: "Pwofil ou anrejistre !",
    nameOrPseudo: "Non oswa pseudo",
    city: "Vil",
    country: "Peyi",
    childrenAges: "Repè laj itil (opsyonèl)",
    childrenAgesExample: "Eg: 6 mwa, 3 an, anfans",
    bio: "Ti prezantasyon",
    bioPlaceholder: "Rakonte ti kras sou tèt ou...",
    save: "Anrejistre",
    saving: "Ap anrejistre",
    
    // Registration and Login pages
    password: "Modpas",
    createAccount: "Kreye kont ou",
    joinCommunity: "Rejwenn Lakou Manman epi adapte eksperyans ou dousman",
    passwordsNotMatch: "Modpas yo pa menm.",
    passwordMinLength: "Modpas la dwe gen omwen 6 karaktè.",
    emailAlreadyInUse: "Imèl sa a deja itilize.",
    passwordTooWeak: "Modpas la twò fèb.",
    emailRequired: "Yon adrès imèl obligatwa.",
    nameRequired: "Yon non oswa tinon obligatwa.",
    genericError: "Yon erè rive. Eseye ankò.",
    googleAccountEmailRequired: "Kont Google la dwe bay yon adrès imèl.",
    googleSignInNotEnabled: "Koneksyon Google la poko aktive sou Firebase.",
    googleSignInFailed: "Nou pa ka kontinye ak Google pou kounye a.",
    networkError: "Gen yon pwoblèm koneksyon entènèt. Verifye rezo a epi eseye ankò.",
    nameExample: "Ex: Michaëlle",
    emailExample: "bonjou@example.com",
    passwordPlaceholder: "Omwen 6 karaktè",
    confirmPassword: "Konfime modpas",
    confirmPasswordPlaceholder: "Menm modpas la",
    cityExample: "Ex: Monreyal",
    countryExample: "Ex: Kanada",
    creatingAccount: "Ap kreye kont",
    createMyAccount: "Kreye kont mwen",
    alreadyHaveAccount: "Ou gen yon kont deja?",
    welcomeBack: "Byenvini anko",
    loginToAccount: "Konekte nan kont Lakou Manman ou",
    forgotPassword: "Bliye modpas?",
    loggingIn: "Ap konekte",
    noAccount: "Ou pa gen kont?",
    invalidCredentials: "Imèl oswa modpas pa kòrèk.",
    continueWithGoogle: "Kontinye ak Google",
    createAccountWithGoogle: "Kreye yon kont ak Google",
    orContinueWithEmail: "oswa kontinye ak imèl ou",
    
    // Theme page
    changeTheme: "Chanje koulè fon",
    chooseTheme: "Chwazi koulè fon ou",
    rosePale: "Roz pal",
    grenadinFonce: "Grenadin fonse",
    peche: "Pèch",
    bleFonce: "Ble fonse",
    cielBleu: "Syèl ble",
    orange: "Oranj",
    soleil: "Solèy",
    
    // Messages
    conversations: "Konvèsasyon",
    sendMessage: "Voye mesaj",
    typeMessage: "Tape mesaj ou...",
    noMessages: "Pa gen mesaj",
    startConversation: "Kòmanse yon konvèsasyon",
    
    // Reviews
    reviews: "Evalyasyon",
    rating: "Nòt",
    writeReview: "Ekri yon evalyasyon",
    yourReview: "Evalyasyon ou",
    noReviews: "Pa gen evalyasyon pou kounye a",
    notRatedYet: "Poko gen nòt",
    beFirstToReview: "Dwe premye moun ki bay evalyasyon ou !",
    
    // Notifications
    markAllAsRead: "Make tout yo li",
    noNotifications: "Pa gen notifikasyon",
    
    // Admin
    adminPanel: "Panno Admin",
    managePosts: "Jere piblikasyon yo",
    manageUsers: "Jere itilizatè yo",
    statistics: "Statistik",
    
    // Common
    loading: "Ap chaje...",
    save: "Anrejistre",
    cancel: "Anile",
    close: "Fèmen",
    delete: "Siprime",
    edit: "Modifye",
    confirm: "Konfime",
    retry: "Eseye ankò",
    back: "Retounen",
    next: "Pwochen",
    submit: "Valide",
    required: "Obligatwa",
    optional: "Opsyonèl",
    
    // Home page buttons
    createAccount: "Kreye kont mwen",
    seeCommunity: "Wè kominote a",
    
    // Stats
    statMothers: "manman nan kominote a",
    statSupport: "espas kestyon & sipò",
    statCities: "vil diaspora aktif",
    statGroups: "gwoup kominotè",
    
    // Section titles
    featuresTitle: "Sa Lakou Manman ofri ou",
    featuresSubtitle: "Tout sa yon manman bezwen, nan yon sèl kote.",
    testimonialsTitle: "Sa manman nou yo di",
    testimonialsSubtitle: "Dekouvri eksperyans kominote a",
    
    // CTA Section
    ctaTitle: "Rejwenn kominote a jodi a",
    ctaDescription: "Anrejistre gratis, kreye pwofil ou, epi kòmanse pataje ak lòt manman yo.",
    ctaButton: "Enskri kounye a",
    ctaLogin: "Mwen gen yon kont deja",
    
    // Footer
    footerNavigation: "Navigasyon",
    footerInformation: "Enfòmasyon",
    footerMedicalDisclaimer: "Tout kontni medikal yo bay la se sèlman pou enfòmasyon.",
    footerMedicalAdvice: "Pou ijans medikal, kontakte yon pwofesyonèl lasante dirèkteman.",
    footerMadeWith: "Fèt ak ❤️ pou manman ayisyèn toupatou nan mond lan",
    
    // Feed page
    feedTitle: "Fil kominote a",
    feedDescription: "Pataje, poze kestyon, epi jwenn sipò nan men lòt manman yo.",
    trendingTopics: "Sijè tandans",
    
    // Feed interactions
    searchPlaceholder: "Chèche kestyon, gwoup oswa mo kle...",
    allCities: "Tout kote",
    loadingPosts: "Ap chaje pòs yo...",
    noPosts: "Pa gen pòs pou kounye a. Kòmanse pataje!",
    city: "Vil",
    
    // Post form
    publishPost: "Pibliye yon pòs",
    publishPostDesc: "Pataje kestyon ou oswa eksperyans ou ak kominote a.",
    questionTitle: "Tit kestyon oswa sijè a",
    category: "Kategori",
    anonymous: "Anonim",
    writePost: "Ekri pòs la...",
    publish: "Pibliye",
    
    // Post tags
    tagSleep: "Dòmi tibebe",
    tagFeeding: "Alimantasyon",
    tagPostpartum: "Post-partum",
    tagCreole: "Manman nan diaspora",
    tagWorkKids: "Travay ak timoun",
    tagHealth: "Lasante",
    tagEducation: "Edikasyon",
    tagCommunity: "Kominote",
    
    // Auth messages
    connectToPost: "Konekte pou pibliye yon pòs.",
    
    // Feed sidebar
    dailyQuestion: "Kesyon jounen an",
    dailyQuestionDesc: "Yon kestyon pou fè kominote a vivan chak jou.",
    activeGroups: "Gwoup aktif",
    
    // Doctor page
    doctorTitle: "Mande Pediat la",
    doctorDesc: "Kontni valide, kestyon jeneral, ak enfòmasyon serye pou manman yo.",
    pediatricAdvice: "Konsèy pediat la",
    pediatricAdviceDesc: "Kontni valide pa pwofesyonèl lasante.",
    validated: "Valide",
    importantNote: "Remak enpòtan",
    medicalDisclaimer: "Remak enpòtan: Seksyon sa a bay enfòmasyon jeneral sèlman, pa konsiltasyon pèsonalize. Pou ijans medikal oswa kestyon ki mande dyagnostik pèsonèl, ale nan yon sèvis lasante dirèkteman.",
    askPediatrician: "Kesyon pou pediat la",
    askPediatricianDesc: "Poze yon kestyon jeneral. Yon pwofesyonèl ap reponn lè li disponib.",
    connectToAsk: "Konekte pou poze yon kestyon.",
    questionSent: "Kestyon ou a ale! Yon pwofesyonèl ap reponn ou nan yon ti tan tou kout.",
    questionTopic: "Tèm kestyon an",
    writeQuestion: "Ekri kestyon jeneral ou isit la...",
    sendQuestion: "Voye kestyon an",
    sending: "Ap voye...",
    emergencyNote: "Pou ijans medikal oswa kestyon ki mande dyagnostik pèsonèl, ale nan yon sèvis lasante dirèkteman.",
    
    // Medical tips
    tipFeverTitle: "Lafyèv lakay tibebe",
    tipFeverText: "Si tibebe a gen mwens pase 3 mwa ak lafyèv, chèche swen medikal vit. Pou rès ka yo, obsève nivo enèji, bweson, ak respire.",
    tipDehydrationTitle: "Siy dezidratasyon",
    tipDehydrationText: "Bouch sèk, pipi ki ra, ak somnolans twòp se siy ki mande atansyon.",
    tipEmergencyTitle: "Kilè pou rele doktè",
    tipEmergencyText: "Lè gen difikilte pou respire, vomisan san kanpe, kriz, oswa tibebe a pa reponn nòmalman.",
    
    // Tools page
    toolsTitle: "Zouti entèraktif",
    toolsDesc: "Kwiz, gid, ti eksperyans itil ki ede manman yo òganize.",
    sleepQuiz: "Quiz dòmi tibebe",
    sleepQuizDesc: "Yon zouti senp men trè angažan pou evalye woutin dòmi.",
    seeMyResult: "Wè rezilta mwen",
    reset: "Rekòmanse",
    upcomingTools: "Lòt zouti k ap vini",
    upcomingSteps: "Pwochen etap",
    
    // Upcoming steps list
    upcomingStep1: "• Suivi téte ak dòmi",
    upcomingStep2: "• Kalendriye devlopman tibebe",
    upcomingStep3: "• Checklist sak tibebe entèraktif",
    upcomingStep4: "• Ti jwèt pou timoun",
    
    // Guides page
    guidesTitle: "Gid ak resous",
    guidesDesc: "Kontni itil pou akonpaye ou pandan matènite, anfans ak adolesans: PDF, lis verifikasyon ak atik pratik.",
    download: "Telechaje",
    downloadSoon: "Byento disponib",
    premiumContent: "Kontni premium k ap vini",
    premiumDesc: "Byento, w ap jwenn gid avanse, lis verifikasyon detaye ak resous espesyal pou manman ki vle ale pi lwen. Rete konekte!",
    
    Guide: "Gid",
    Article: "Atik",
    Checklist: "Lis verifikasyon",
    PDF: "PDF",
    guide: "Gid",
    article: "Atik",
    checklist: "Lis verifikasyon",
    pdf: "PDF",
    
    newMom: "Nouvo manman",
    practical: "Pratik",
    sleep: "Dòmi",
    feeding: "Alimantasyon",
    health: "Lasante",
    
    guideNewMomTitle: "Premye pa ak tibebe",
    guideNewMomDesc: "Yon gid pou akonpaye ou pandan twa premye mwa yo ak tibebe a epi ede w nan premye jou yo.",
    guideChecklistBabyTitle: "Lis verifikasyon pou tibebe",
    guideChecklistBabyDesc: "Yon lis pratik pou soti ak tibebe a san ou pa bliye anyen. Tout sa ou bezwen nan sak la.",
    guideSleepRoutineTitle: "Woutin dòmi tibebe",
    guideSleepRoutineDesc: "Yon modèl senp pou mete bon abitid dòmi an plas, etap pa etap, pou nwit ki pi kalm.",
    guideFeedingTitle: "Alimantasyon tibebe 0-12 mwa",
    guideFeedingDesc: "Kisa pou bay tibebe a selon laj li: tete, lèt fòmil ak premye manje solid.",
    guideBathSafetyTitle: "Swen kòd lonbrit",
    guideBathSafetyDesc: "Kijan pou pran swen kòd lonbrit tibebe a jouk li tonbe, ak bon konsèy ijyèn ak sekirite.",
    guideChildRoutineTitle: "Woutin ak repè pou timoun",
    guideChildRoutineDesc: "Konsèy senp sou dòmi, lekòl, alimantasyon, ekran ak òganizasyon lavi chak jou timoun yo.",
    guideTeenDialogueTitle: "Pi byen akonpaye adolesan ou",
    guideTeenDialogueDesc: "Repè pou kenbe dyalòg la, mete limit, konprann emosyon yo epi konnen kilè pou chèche èd.",
    featureDoctor: "Aksè ekspè sante",
    featureDoctorDesc: "Konsilte pedyat ak lòt pwofesyonèl kalifye an liy oswa an pèsòn.",
    step4Title: "Konsilte yon ekspè sante",
    step4Desc: "Jwenn konsèy nan men pedyat ak lòt pwofesyonèl selon bezwen ou.",
    
    // Individual content types
    Guide: "Gid",
    Article: "Atik",
    Checklist: "Checklist",
    PDF: "PDF",
    guide: "Gid",
    article: "Atik",
    checklist: "Checklist",
    pdf: "PDF",
    
    // Quiz questions
    quizQ1: "Konbyen fwa tibebe w reveye an mwayèn lannuit?",
    quizQ1Opt1: "0-1 fwa",
    quizQ1Opt2: "2-3 fwa", 
    quizQ1Opt3: "4 fwa oswa plis",
    quizQ2: "Eske tibebe a gen yon abitid ki pou fè li dòmi chak swa?",
    quizQ2Opt1: "Wi, prèske toujou",
    quizQ2Opt2: "Pafwa",
    quizQ2Opt3: "Non",
    quizQ3: "Ki sa tibebe a fè anvan dòmi?",
    quizQ3Opt1: "Woutin kalm",
    quizQ3Opt2: "Sa depann",
    quizQ3Opt3: "Anpil eksitasyon / ekran / bri",
    
    // Quiz results
    goodSleepBase: "Bon baz dòmi",
    goodSleepText: "Woutin nan sanble deja sou bon chimen. Kontinye ak lè fiks, limyè ba, ak rityèl kalm avan dòmi.",
    needsImprovement: "Bezwen amelyore",
    needsImprovementText: "Kèk ajistman ka ede. Esaye yon ritin plis koyèran ak mwens stimilasyon avan dòmi.",
    needsWork: "Anpil travay pou fè",
    needsWorkText: "Konsidere yon konsiltasyon pwofesyonèl. Yon ritin strik ak yon anviwònman dòmi optimal enpòtan.",
    
    // Tool ideas
    checklistBaby: "Checklist sak tibebe",
    interactiveGuideNewMoms: "Gid entèraktif pou nouvo manman",
    feedingSleepTracking: "Suivi tétée / dòmi",
    babyDevelopmentCalendar: "Kalendriye devlopman tibebe",
    members: "manm",
    posts: "pòs",
    seePosts: "Gade post",
    
    // Groups page
    groupsTitle: "Gwoup sipò",
    groupsDescription: "Piti kominote tematik pou kreye plis lyen ak diskisyon pi pwofond.",
    joiningGroup: "Ap rejwenn...",
    joinGroup: "Rejwenn gwoup la",
    alreadyMember: "Deja manm",
    activeGroups: "Gwoup aktif",
    discoverGroups: "Gwoup pou rejwenn",
    noActiveGroups: "Ou poko fè pati okenn gwoup pou kounye a.",
    noDiscoverGroups: "Ou deja rejwenn tout gwoup ki disponib yo.",
    signInToJoinGroups: "Konekte pou ka rejwenn yon gwoup.",
    
    // Group names
    groupNewborn: "Nesans ak nouvo ne",
    groupNewbornDesc: "Espas pou kestyon ak repè sou premye semèn lavi yo.",
    groupChildren: "Anfans",
    groupChildrenDesc: "Echanj sou lasante, lekòl, devlopman, woutin ak lavi chak jou timoun yo.",
    groupTeens: "Adolesans",
    groupTeensDesc: "Yon espas pou pale sou lekòl, emosyon, dyalòg, limit ak byennèt pandan adolesans.",
    groupPostpartum: "Post-partum", 
    groupPostpartumDesc: "Sipò apre akouchman: kò, emosyon, rekiperasyon ak adaptasyon.",
    groupDiaspora: "Diaspora",
    groupDiasporaDesc: "Konekte ak kominote ayisyen nan mond lan.",
    groupFeeding: "Alimantasyon",
    groupFeedingDesc: "Konsèy sou alimantasyon, bay tete ak nitrisyon chak jou.",
    groupWorkFamily: "Travay ak fanmi",
    groupWorkFamilyDesc: "Jwenn ekilib ant travay, chay mantal ak lavi fanmi.",
    groupAutismParents: "Paran timoun otis",
    groupAutismParentsDesc: "Yon espas sipò, resous ak pataj pou paran k ap akonpaye yon timoun otis chak jou.",
    groupGriefLoss: "Dèy ak pèt",
    groupGriefLossDesc: "Yon espas sansib ak byenveyan pou jwenn koute, sipò ak rekonfò lè gen yon pèt.",
    groupDefaultDescription: "Espas pou kestyon, eksperyans, ak sipò ant manm yo.",
    loadingGroup: "Ap chaje gwoup la",
    noPostsInGroup: "Pa gen pòs nan gwoup sa a ankò. Kòmanse pataje!",
    groupInformation: "Enfòmasyon gwoup",
    leaveGroup: "Kite gwoup la",
    leavingGroup: "Ap kite...",
    inviteMembers: "Envite manm yo",
    copyInviteLink: "Kopye lyen envitasyon an",
    inviteLinkCopied: "Lyen envitasyon an kopye",
    inviteLinkCopyError: "Pa ka kopye lyen an kounye a",
    pinnedPosts: "Pòs epingle",
    noPinnedPosts: "Pa gen pòs epingle pou kounye a.",
    noMembersYet: "Pa gen manm pou kounye a.",
    openingConversation: "Ap ouvri...",
    viewLessMembers: "Wè mwens manm",
    groupRules: "Règ gwoup la",
    groupRuleRespect: "Respekte chak moun, chak chemen lavi ak chak opinyon.",
    groupRuleKindness: "Kenbe yon ton dous epi evite atak pèsonèl.",
    groupRulePrivacy: "Pa pataje enfòmasyon prive manm yo deyò gwoup la.",
    groupRuleMedical: "Nenpòt konsèy medikal ijan dwe toujou verifye ak yon pwofesyonèl lasante.",
    mothers: "manman",
    discussions: "diskisyon",
    
    // Stripe Invoice Information
    invoiceCompanyName: "Lakou Manman S.A.",
    invoiceAddress: "Pòtoprens, Ayiti",
    invoiceEmail: "contact@lakou-manman.com",
    invoicePhone: "+509 32 58 93 91",
    invoiceWebsite: "www.lakou-manman.com",
    invoiceTaxId: "HT-123456789",
    
    // Invoice Footer Text
    invoiceFooterTitle: "Lakou Manman - Kominote manman ayisyen yo",
    invoiceFooterDesc: "Mèsi pou konfyans ou. Ansanm nou bati yon kominote solidè.",
    invoiceFooterNote: "Tout pri yo an HTG. Taxes enkli si aplikab.",
    invoicePaymentInfo: "Pèman sekirize trete ak Stripe",
    invoiceSupportContact: "Pou tout kesyon : contact@lakou-manman.com",
    
    // Payment Form
    paymentError: "Yon erè rive pandan pèman an",
    paymentSuccessMessage: "Pèman reyisi ak siksè !",
    processingPayment: "Ap trete pèman an...",
    payNow: "Peye kounye a",
    paymentProcessing: "Trètman pèman an",
    paymentComplete: "Pèman termine",
    paymentFailed: "Echek pèman",
    downloadReceipt: "Telechaje resi a",
    
    // MonCash Payment
    yourMonCashNumber: "Nimewo MonCash ou",
    yourOrangeMoneyNumber: "Nimewo Orange Money ou",
    yourNatCashNumber: "Nimewo NatCash ou",
    important: "Enpòtan",
    smsConfirmationText: "Ou pral resevwa yon mesaj SMS konfimasyon sou nimewo sa a pou valide peman an.",
    amountDebitedText: "Kob la pral debite nan kont MonCash/Orange Money ou.",
    validPhoneRequired: "Tanpri antre yon nimewo telefòn ki valab.",
    paymentMethodLabel: "Metòd pèman",
    moncashOption: "MonCash",
    orangeMoneyOption: "Orange Money",
    natcashOption: "NatCash",
    paymentHeaderMoncash: "Pèman MonCash",
    paymentHeaderOrange: "Pèman Orange Money",
    paymentHeaderNatcash: "Transfè NatCash pou verifye",
    securePaymentMoncash: "Pèman sekirize atravè MonCash",
    securePaymentOrange: "Pèman sekirize atravè Orange Money",
    securePaymentNatcash: "Transfè NatCash reyèl ak verifikasyon manyèl",
    payWithMonCash: "Peye ak MonCash",
    payWithOrangeMoney: "Peye ak Orange Money",
    payWithNatCash: "Mwen peye ak NatCash",
    natcashReferenceLabel: "Referans NatCash",
    natcashReferencePlaceholder: "Eg: NAT123456 oswa referans ou resevwa apre pèman an",
    natcashReceiverNumber: "Nimewo NatCash vandè a",
    natcashReceiverUnavailable: "Poko gen nimewo NatCash ki configuré pou atik sa a. Kontakte sipò a anvan ou peye.",
    natcashPaymentPending: "TRANSFÈ NATCASH POU VERIFYE !",
    natcashManualMode: "Transfè reyèl ak verifikasyon manyèl",
    paymentReferenceRequired: "Tanpri antre referans tranzaksyon NatCash la.",
    paymentNoteLabel: "Nòt sou pèman an",
    paymentNotePlaceholder: "Eg: mwen itilize nimewo mari mwen pou voye pèman an",
    moncashPaymentPending: "PÈMAN MONCASH AN KOU!",
    moncashPaymentSuccess: "PÈMAN MONCASH REYISI!",
    transactionDetails: "Detay Transaksyon:",
    article: "Atik",
    amount: "Montan",
    lakouManmanCommission: "Komisyon Lakou Manman",
    sellerAmount: "Montan Vandè",
    paymentInfo: "Enfòmasyon Peman",
    transactionId: "Transaksyon ID",
    reference: "Referans",
    phone: "Telefòn",
    method: "Metòd",
    mode: "Mòd",
    realMoncash: "MonCash Reyèl",
    demoMode: "Mòd Demo",
    date: "Dat",
    downloadInvoice: "Ou vle telechaje resi a?",
    actionRequired: "AKSION NESESÈ:",
    checkSmsText: "Verifye SMS ou sou",
    receiveMoncashText: "Ou dwe resevwa yon mesaj MonCash pou konfime pèman sa a.",
    replyYesText: "Reponn \"WI\" nan SMS pou finalize acha an.",
    downloadProvisionalInvoice: "Ou vle telechaje yon resi pwovizyonèl?",
    paymentError: "ERÈ PÈMAN",
    errorOccurred: "Yon erè te fèt",
    error: "ERÈ",
    paymentProcessingError: "Enposib poun trete pèman an. Tanpri reeseye.",
    
    // Invoice
    invoiceTitle: "RESI LAKOU MANMAN",
    invoiceNumber: "Nimewo",
    clientInfo: "ENFÒMASYON KLIYAN",
    name: "Non",
    articleDetails: "DETAY ATIK",
    quantity: "Kantite",
    price: "Pri",
    total: "Total",
    financialSummary: "REKAPITILASYON FINANSYE",
    subtotal: "Sou-total",
    totalPaid: "TOTAL PEYE",
    platformSubtitle: "Platfòm Kominotè Ayisyen",
    thankYouForTrust: "Mèsi pou konfyans ou!",
    contact: "Kontak",
    
    // Seller Form
    sellerMonCashNumber: "Nimewo MonCash (vandè)",
    receivePaymentsText: "Pou resevwa pèman yo dirèkteman sou kont MonCash ou",
    sellerNatCashNumber: "Nimewo NatCash (vandè)",
    receiveNatCashPaymentsText: "Pou resevwa pèman NatCash yo dirèkteman sou kont NatCash ou",
    
    // Delivery Options
    deliveryOptions: "Opsyon livrezon",
    pickup: "Retrè sou plas",
    pickupDescription: "Rekipere dirèkteman apre vandè a",
    homeDelivery: "Livrezon lakay",
    deliveryDescription: "Livrezon nan adrès ou",
    free: "GRATIS",
    calculated: "kalKile",
    deliveryAddress: "Adres livrezon",
    deliveryAddressPlaceholder: "Antre adrès konplè ou...",
    deliveryInfo: "Enfòmasyon livrezon",
    deliveryFeeCalculated: "Frè livrezon yo pral kalkile selon distans la",
    deliveryFee: "Frè livrezon",
    
    // Groups
    groupJoined: "Anndan Gwoup la !",
    groupJoinedMessage: "Ou rejwenn gwoup la avèk siksè",
    errorJoiningGroup: "Erè",
    errorJoiningGroupMessage: "Enposib pou rejwenn gwoup la",
    welcomeToGroup: "Byenvini nan gwoup la !",
    members: "memb",
    created: "Kreye",
    joinGroup: "Rejwen yon gwoup",
    member: "Memb",
    share: "Pataje",
    settings: "Paramèt",
    createPost: "Kreye yon mesaj",
    postPlaceholder: "Pataje yon bagay ak gwoup la...",
    publish: "Pibliye",
    photo: "Foto",
    video: "Videyo",
    reviews: "avi",
    admin: "Admin",
    moderator: "Moderatè",
    groupInfo: "Enfòmasyon gwoup",
    location: "Lokalizasyon",
    activity: "Aktivite",
    veryActive: "Trè aktif",
    contactAdmin: "Kontakte admin",
    groupAdmin: "Admin gwoup",
    message: "Mesaj",
    email: "Imèl",
    
    // Pediatrician
    bookAppointment: "Pran randevou",
    consultationVideo: "Konsiltasyon vidyo",
    sendMessage: "Voye mesaj",
    educationalVideos: "Videyo edikatif",
    articlesResources: "Atik ak resous",
    contactDoctor: "Kontakte doktè a",
    yourName: "Non ou",
    yourEmail: "Imèl ou",
    yourPhone: "Telefòn ou",
    consultationReason: "Rezon konsiltasyon an",
    message: "Mesaj",
    namePlaceholder: "Antre non ou",
    emailPlaceholder: "imèl@ou.com",
    reasonPlaceholder: "Eg: Kontwòl rutin, lafyèv, etc.",
    messagePlaceholder: "Deskri sitiyasyon ou...",
    messageSent: "Mesaj voye avèk siksè !",
    quickContact: "Kontak rapid",
    callNow: "Rele kounye a",
    whatsapp: "WhatsApp",
    sendEmail: "Voye imèl",
    pediatriciansDirectory: "Pedyat ki disponib",
    pediatriciansDirectoryDesc: "Espas sa a louvri pou plizyè pedyat, òganize pa vil.",
    allCities: "Tout vil yo",
    selectPediatrician: "Chwazi pedyat sa a",
    selectedPediatrician: "Pedyat chwazi a",
    city: "Vil",
    consultationFees: "Tarif konsiltasyon",
    inPerson: "An pèsòn",
    clinicConsultation: "Konsiltasyon klinik",
    virtual: "Vityèl",
    videoConsultation: "Konsiltasyon vidyo",
    emergency: "Ijans",
    emergencyConsultation: "Konsiltasyon ijans",
    availability: "Disponiblite",
    monday: "Lendi",
    tuesday: "Madi",
    wednesday: "Mèkredi",
    thursday: "Jedi",
    friday: "Vandredi",
    saturday: "Samdi",
    sunday: "Dimanch",
    hospitalInfo: "Enfòmasyon lopital",
    getDirections: "Jwenn itinèr",
    views: "vwa",
    
    // Tools
    toolsTitle: "Zouti pou manman",
    toolsDescription: "Zouti pratik pou ede ou nan lavi chak jou kòm manman",
    availableTools: "Zouti ki disponib",
    selectTool: "Chwazi yon zouti",
    selectToolDesc: "Chwazi yon zouti nan lis la pou kòmanse",
    pregnancyCalculator: "Kalkilatris gwosès",
    pregnancyCalculatorDesc: "Kalkile dat akouchman ou epi swiv gwosès ou",
    babyGrowth: "Kwasans tibebe",
    babyGrowthDesc: "Swiv kwasans ak devlopman tibebe ou",
    temperatureTracker: "Swivi tanperati",
    temperatureTrackerDesc: "Anrejistre epi swiv tanperati pitit ou",
    emergencyContacts: "Kontak ijans",
    emergencyContactsDesc: "Jwenn kontak ijans pedyatrik rapidman",
    vaccinationSchedule: "Kalandriye vaksen",
    vaccinationScheduleDesc: "Modèl kalandriye vaksen pou swiv vaksen depi nan anfans rive nan adolesans",
    vaccinationModelTitle: "Modèl kalandriye vaksen",
    ageGroup: "Gwoup laj",
    recommendedVaccines: "Vaksen rekòmande",
    vaccinationReminder: "Kalandriye sa a se yon modèl enfòmatif. Toujou verifye li ak yon pedyat oswa sant sante.",
    vaccinationBirthStage: "Lè tibebe fèk fèt",
    vaccination6WeeksStage: "6 semèn",
    vaccination10WeeksStage: "10 semèn",
    vaccination14WeeksStage: "14 semèn",
    vaccination9MonthsStage: "9 mwa",
    vaccination12MonthsStage: "12 mwa",
    vaccination15MonthsStage: "15 mwa",
    vaccination18MonthsStage: "18 mwa",
    vaccination4To6YearsStage: "4 rive 6 an",
    vaccination9To14YearsStage: "9 rive 14 an",
    vaccination15To18YearsStage: "15 rive 18 an",
    vaccinationBirthVaccines: "BCG, Polyo 0, Epatit B selon pwotokòl lokal la",
    vaccination6WeeksVaccines: "Pentavalan 1, Polyo 1, Rotaviris 1, Nemokòk 1",
    vaccination10WeeksVaccines: "Pentavalan 2, Polyo 2, Rotaviris 2, Nemokòk 2",
    vaccination14WeeksVaccines: "Pentavalan 3, Polyo 3, Nemokòk 3",
    vaccination9MonthsVaccines: "Lawoujòl-Ribeyòl, Vitamin A",
    vaccination12MonthsVaccines: "Rapèl ak swivi selon sant sante a",
    vaccination15MonthsVaccines: "Rapèl pou premye ane timoun nan selon pwotokòl lokal la",
    vaccination18MonthsVaccines: "DTC/Polyo/ROR oswa lòt rapèl selon pwogram nasyonal la",
    vaccination4To6YearsVaccines: "Rapèl anvan lekòl selon pwogram nasyonal la",
    vaccination9To14YearsVaccines: "Vaksen HPV ak lòt dòz rekòmande selon disponiblite ak pwotokòl lokal la",
    vaccination15To18YearsVaccines: "Rapèl pou adolesan, tetanòs-difterik ak mete kanè a ajou selon sant sante a",
    nutritionGuide: "Gid nitrisyon",
    nutritionGuideDesc: "Konsèy nitrisyon selon laj pitit ou",
    developmentMilestones: "Etap devlopman",
    developmentMilestonesDesc: "Swiv etap enpòtan nan devlopman pitit ou",
    communitySupport: "Sipò kominotè",
    communitySupportDesc: "Konekte ak lòt manman pou jwenn sipò",
    lastPeriodDate: "Dat dènye règ yo",
    cycleLength: "Dire sik la (jou)",
    pregnancyResults: "Rezilta gwès",
    weeks: "Sèmenn",
    days: "Jou",
    trimester: "Trimès",
    daysLeft: "Jou ki rete",
    dueDate: "Dat akouchman prevwa",
    birthDate: "Dat nesans",
    birthWeight: "Pwa nesans (kg)",
    currentWeight: "Pwa aktyèl (kg)",
    currentHeight: "Wotè aktyèl (cm)",
    growthResults: "Rezilta kwasans",
    daysOld: "Jou",
    monthsOld: "Mwa",
    weightGain: "Pran pwa (kg)",
    dailyGain: "Pran pa jou (g)",
    growthNormal: "Kwasans nòmal",
    consultDoctor: "Konsilte yon pwofesyonèl lasante",
    temperature: "Tanperati (°C)",
    symptoms: "Sentòm asosye",
    cough: "Touse",
    runnyNose: "Nen k ap koule",
    headache: "Maltèt",
    fatigue: "Fatig",
    lossAppetite: "Pèt apeti",
    vomiting: "Vomisman",
    hypothermia: "Ipotèmi",
    normal: "Nòmal",
    fever: "Lafyèv lejè",
    moderateFever: "Lafyèv modere",
    highFever: "Gwo lafyèv",
    recommendations: "Rekomandasyon",
    monitorTemp: "Siveye tanperati a chak 4 èdtan",
    hydrate: "Bay anpil likid",
    rest: "Repo rekòmande",
    giveMedication: "Bay parasetamol si nesesè",
    monitorClosely: "Siveye l byen",
    consultIfWorsens: "Konsilte si lafyèv la dire plis pase 48 èdtan",
    consultImmediately: "Konsilte yon doktè imedyatman",
    emergencySigns: "Siy ijans",
    keepHydrated: "Kenbe bon idratasyon",
    difficultyBreathing: "Difikilte respire",
    blueLips: "Lèv oswa vizaj ble",
    unconscious: "Pèt konesans",
    seizures: "Kriz",
    severeBleeding: "Senyen anpil",
    callEmergency: "Rele ijans (114)",
    emergencyServices: "Sèvis ijans",
    pediatricEmergency: "Ijans pediyatrik",
    poisonControl: "Sant kont pwazon",
    drBeaubrun: "Dr Beaubrun (Pedyat)",
    hospitalEmergency: "Ijans Lopital",
    call: "Rele",
    
    // Header & Footer
    aboutUs: "A pwopo",
    howItWorks: "Kouman li fonksyone",
    features: "Karakteristik",
    testimonials: "Temwanyaj",
    helpCenter: "Sant èd",
    footerHelpCenter: "Sant èd",
    footerContact: "Kontak",
    footerAboutUs: "A pwopo",
    footerLegal: "Legal",
    footerPrivacyPolicy: "Politik konfidansyalite",
    footerTermsOfService: "Kondisyon itilizasyon",
    faq: "FAQ",
    reportIssue: "Signale yon pwoblèm",
    privacyPolicy: "Politik konfidansyalite",
    termsOfService: "Kondisyon itilizasyon",
    cookiePolicy: "Politik cookies",
    guidelines: "Gid kominotè",
    groups: "Gwoup",
    platform: "Platfòm",
    support: "Sipò",
    services: "Sèvis",
    legal: "Legal",
    footerDescription: "Lakou Manman se platfòm referans pou manman ayisyen. Konekte ou, pataje, epi aksede resous presye pou byenèt ou epi pou timoun ou.",
    communityFeature: "Kominote Aktif",
    communityFeatureDesc: "Rejini milman manman",
    expertFeature: "Aksè Ekspè",
    expertFeatureDesc: "Konsilte pedyat, sikològ, jinekològ ak lòt pwofesyonèl kalifye",
    safetyFeature: "Sekirite",
    safetyFeatureDesc: "Platfòm sekirize epi modere",
    allRightsReserved: "Tout dwa rezève.",
    madeWith: "Fè ak",
    forHaitianMoms: "pou manman ayisyen",
    footerCommunityPhrase: "Yon kominote manman ayisyen nan mond antye pou pataje, aprann epi sipòte youn lòt.",
    privacy: "Konfidansyalite",
    terms: "Kondisyon",
    cookies: "Cookies",
    community: "Kominote",
    safety: "Sekirite",
    inclusion: "Enklizyon",
    excellence: "Ekselans",
    innovation: "Inovasyon",
    safetyDesc: "Pwoteje epi akonpaye manm yo nan yon espas ki serye.",
    supportDesc: "Ofri sipò, konpreyansyon ak akonpayman pou chak manman.",
    inclusionDesc: "Bay valè ak tout manman ayisyèn, kèlkeswa kote yo ye ak chemen lavi yo.",
    excellenceDesc: "Bati sèvis ki itil, senp epi ki gen bon kalite.",
    innovationDesc: "Kreye solisyon dijital ki reponn ak reyalite manman ayisyèn yo.",
    helpDescription: "Jwenn repons, etap ak resous itil rapidman.",
    searchHelp: "Chèche nan sant èd la...",
    quickHelp: "Èd rapid",
    gettingStarted: "Premye etap yo",
    gettingStartedDesc: "Etap ki pi enpòtan pou byen kòmanse sou Lakou Manman.",
    communityHelpDesc: "Kesyon sou gwoup, piblikasyon ak echanj ant manman yo.",
    boutiqueHelpDesc: "Tout sa ou dwe konnen sou acha, vant, peman ak livrezon.",
    pediatreHelpDesc: "Èd pou konsiltasyon, randevou ak kontak pedyatrik.",
    safetyHelpDesc: "Konsèy sou sekirite, konfidansyalite ak siyalisyon.",
    toolsHelpDesc: "Èd pou itilize zouti pratik platfòm nan.",
    stillNeedHelp: "Ou bezwen plis èd?",
    supportTeam: "Ekip nou an disponib pou gide ou.",
    aboutDescription: "Lakou Manman se yon kominote dijital ki fèt pou enfòme, sipòte epi konekte manman ayisyèn yo.",
    ourMission: "Misyon nou",
    missionDescription: "Kreye yon espas dijital ki bay sipò, zouti itil ak opòtinite konkrè pou manman ayisyèn yo.",
    ourValues: "Valè nou yo",
    activeMoms: "Manman aktif",
    expertPartners: "Patnè ak ekspè",
    dailyPosts: "Piblikasyon chak jou",
    satisfaction: "To satisfaksyon",
    ourTeam: "Ekip nou an",
    joinUs: "Vin jwenn nou",
    joinDescription: "Patisipe nan yon kominote ki mete manman ayisyèn yo, bezwen yo ak rèv yo an valè.",
    getStarted: "Kòmanse",
    buyerLocation: "Lokalizasyon ou",
    buyerLocationPlaceholder: "Eg: Pòtoprens, Delma, Petyonvil...",
    sellerLocation: "Lokalizasyon vandè a",
    estimatedDistance: "Distans estime",
    deliveryEstimateUnavailable: "Nou pa ka estime frè livrezon yo otomatikman ak lokalizasyon sa a.",
    buyerLocationRequired: "Tanpri chwazi lokalizasyon ou pou livrezon an.",
}
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(DEFAULT_LANGUAGE);
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
    // Load saved language from localStorage
    if (typeof window === "undefined") {
      return;
    }

    try {
      const savedLanguage = normalizeLanguage(window.localStorage.getItem(LANGUAGE_STORAGE_KEY));
      setLanguage(savedLanguage);
      window.localStorage.setItem(LANGUAGE_STORAGE_KEY, savedLanguage);
    } catch (error) {
      console.warn("Unable to restore saved language:", error);
      setLanguage(DEFAULT_LANGUAGE);
    }
  }, []);

  const changeLanguage = (lang) => {
    const nextLanguage = normalizeLanguage(lang);
    setLanguage(nextLanguage);

    if (typeof window === "undefined") {
      return;
    }

    try {
      window.localStorage.setItem(LANGUAGE_STORAGE_KEY, nextLanguage);
    } catch (error) {
      console.warn("Unable to persist selected language:", error);
    }
  };

  const t = (key) => {
    const resolvedLanguage = normalizeLanguage(language);
    const activeTranslations = translations[resolvedLanguage] || translations[DEFAULT_LANGUAGE] || {};
    const fallbackTranslations = translations[DEFAULT_LANGUAGE] || {};
    return activeTranslations[key] || fallbackTranslations[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
